#!/usr/bin/env python3
"""tools/extract/butterfly_flap_ctrl.py — bake the town butterflies' FLAP-TRIGGER
control stream from a seed-pinned retail capture.

PORT-DEBT(butterfly-flutter-trigger).  The butterfly's vertical flutter is the
shared case-3 "jump" FSM (the SAME physics as Arche's jump, ported in
character.c) with butterfly constants (impulse -32000, cap +16000, fall +2000,
rise grav held +1000 / free +4000, windup 4) — that PHYSICS is RE'd and ported
as real logic in butterfly.c.  What is *captured* here is only the TRIGGER: when
the autonomous wander AI issues the flap (the body+0x38 flap state and the
cmd_2==8 "flap held" control), which emerges from the shared TERRAIN-AWARE mover
(0x43f880 scans the collision grid downward for the floor and flaps to hold ~8000
units of altitude above it).  That mover is the freeroam character mover — until
it is ported, the per-tick (state3, cmd2_held) control is taken from a retail
capture.  Because the port boots OSS_RNG_DEFAULT_SEED and the retail harness pins
the same seed, the butterfly spawn + flap cadence are deterministic and identical
to retail.osr (the studio reference), so replaying this control reproduces the
butterfly bob bit-exact over the settled town.

Two bits per butterfly per sim-tick:
    bit (2*lane+0) = body+0x38 flap state == 3 (in the flap FSM; resets the windup)
    bit (2*lane+1) = cmd_2 == 8           (flap "held": rise grav 1000, else 4000)
The PHYSICS (butterfly.c) consumes these to drive the real RE'd FSM — verified
bit-exact (0 vvel mismatches / 1824 ticks x 4 butterflies) vs the capture.

Regenerate (when the capture is refreshed) from a seed-pinned field capture of
the butterfly AI 0x47b990 (the bstate / cmd_2 fields):
    FRAMES=$(python3 -c "print(','.join(str(f) for f in range(1420,2400)))")
    nix develop --command python3 tools/frida_capture.py \\
      --no-turbo --lockstep --seed-pin \\
      --input-trace tests/scenarios/in-game-intro/trace-retail.jsonl \\
      --field-spec tools/flow/butterfly_capture_fields.json --field-spec-only \\
      --call-trace --call-trace-frames "$FRAMES" \\
      --max-frames 2600 --duration-ms 105000 \\
      --run-dir runs/butterfly-flutter --exact-run-dir --remote cutestation.soy:27042
    nix develop --command python3 tools/extract/butterfly_flap_ctrl.py

This is RE'd structural behaviour read off the user's own game under a pinned
seed — not a redistributed asset.  Retire when the terrain mover lands.
"""
import json
import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CAP = os.path.join(ROOT, "runs", "butterfly-flutter", "call_trace.jsonl")
OUT = os.path.join(ROOT, "src", "butterfly_flap_ctrl.h")


def main():
    if not os.path.exists(CAP):
        sys.exit(f"capture not found: {CAP}\n(re-capture per the module docstring)")
    rows = [json.loads(l) for l in open(CAP)]
    bf = [r for r in rows if r["f"].get("code") == "0xe29a"]
    bytick = defaultdict(list)
    for r in bf:
        bytick[r["sim_tick"]].append(r)
    # the 4 butterflies appear in a stable band-walk order each tick (the `seq`)
    tracks = defaultdict(dict)
    for t in sorted(bytick):
        for i, r in enumerate(sorted(bytick[t], key=lambda r: r["seq"])):
            tracks[i][t] = r["f"]
    nlanes = len(tracks)
    if nlanes != 4:
        sys.exit(f"expected 4 butterfly lanes, got {nlanes}")
    nt = min(max(tracks[i]) for i in range(4)) + 1
    spawn_wx = [tracks[i][0]["wx"] for i in range(4)]

    ctrl = []
    for t in range(nt):
        b = 0
        for i in range(4):
            d = tracks[i].get(t)
            if not d:
                continue
            if (d["bstate"] & 0xFFFF) == 3:
                b |= 1 << (2 * i)
            if d["cmd_2"] == 8:
                b |= 1 << (2 * i + 1)
        ctrl.append(b)

    with open(OUT, "w") as o:
        o.write("/*\n")
        o.write(" * butterfly_flap_ctrl.h — GENERATED by tools/extract/butterfly_flap_ctrl.py.\n")
        o.write(" * Do not edit by hand.  PORT-DEBT(butterfly-flutter-trigger): the captured\n")
        o.write(" * per-tick flap TRIGGER for the 4 town butterflies (the real flutter PHYSICS\n")
        o.write(" * is RE'd logic in butterfly.c; only the terrain-mover trigger is captured).\n")
        o.write(" * 2 bits / butterfly / sim-tick: bit(2*lane)=flap-state-3, bit(2*lane+1)=cmd2-held.\n")
        o.write(" * Lanes match BUTTERFLY_FLAP_CTRL_WX (spawn worldX) in band order.\n")
        o.write(" */\n")
        o.write("#ifndef OSS_BUTTERFLY_FLAP_CTRL_H\n#define OSS_BUTTERFLY_FLAP_CTRL_H\n\n")
        o.write("#include <stdint.h>\n\n")
        o.write(f"#define BUTTERFLY_FLAP_CTRL_NTICKS {nt}\n\n")
        o.write("static const int32_t BUTTERFLY_FLAP_CTRL_WX[4] = {")
        o.write(",".join(str(w) for w in spawn_wx))
        o.write("};\n\n")
        o.write("static const uint8_t BUTTERFLY_FLAP_CTRL[BUTTERFLY_FLAP_CTRL_NTICKS] = {\n")
        for i in range(0, nt, 16):
            o.write("    " + ",".join("0x%02x" % c for c in ctrl[i:i + 16]) + ",\n")
        o.write("};\n\n#endif /* OSS_BUTTERFLY_FLAP_CTRL_H */\n")
    print(f"wrote {OUT}: NTICKS={nt} lanes_wx={spawn_wx}")


if __name__ == "__main__":
    main()
