#!/usr/bin/env python3
"""tools/extract/info_palette_swap_tables.py — extract the CROSS-SLOT palette-swap
tables (FUN_00417bc0, the info-entry +8 consumer) from the retail EXE's .rdata.

Background (docs/findings/errands-render-gaps.md §3).  A sprite bank's info-entry
+8 holds a pointer to a 520-byte palette-transform table consumed by FUN_00417bc0:

    first u16 (table[0:2]) = the SOURCE selector
      == 0  -> remap entries WITHIN the bank's own (embedded) palette
               (the NPC colour-variant body-bank shift; modelled separately as
               the equivalent pixel-index remap, see npc_palette_remap.py).
      != 0  -> a CROSS-SLOT swap: copy palette entries from the slot whose POOL
               index == first_u16 (ar_pool_get_slot) into this bank's palette.

    then, for i = 0,1,2,...:
      src_idx = table[0x102 + i]   ; stop when src_idx == 0
      dst_idx = table[0x002 + i]
      palette[dst_idx] = source_palette[src_idx]

The CROSS-SLOT case is the per-room floor palette: the errands floor banks 0x187/
0x188 (clones of the town floor res 0x769/0x76a) carry +8 = &DAT_00675500 whose
first u16 = 0x186 -> they slice the town floor PIXELS against res 0x76b's (greyer)
palette.  The town draws the same pixels against their own warm palette.

This extracts ONLY the cross-slot tables (first u16 != 0) referenced by the port's
group3 DATA_SET events, as (src_pool, [(dst,src)...]) — the meaningful content of
each table.  RE'd structural data copied out of the user's own sotes.exe .rdata
(the world_tables_data.c pattern), NOT a redistributed asset.

Usage:
    nix develop --command python3 tools/extract/info_palette_swap_tables.py \\
        [vendor/unpacked/sotes.unpacked.exe]   # emits C to stdout
"""
import re
import sys

# .rdata: VMA 0x5cc000, file offset 0x1cc000 (objdump -h of the unpacked exe).
RDATA_VMA = 0x5cc000
RDATA_FOFF = 0x1cc000


def va_to_off(va):
    return RDATA_FOFF + (va - RDATA_VMA)


def parse_table(data, va):
    """Return (src_pool, [(dst,src),...]) parsing FUN_00417bc0's table format."""
    t = data[va_to_off(va):va_to_off(va) + 0x208]   # 520 bytes
    src_pool = t[0] | (t[1] << 8)
    pairs = []
    for i in range(256):
        src_idx = t[0x102 + i]
        if src_idx == 0:
            break
        dst_idx = t[0x002 + i]
        pairs.append((dst_idx, src_idx))
    return src_pool, pairs


def data_set_vas():
    """The distinct DATA_SET payload VAs the port replays (asset_register.c)."""
    vas = []
    for ln in open("src/asset_register.c"):
        if "AR_INFO_EVT_DATA_SET" in ln:
            m = re.search(r'(0x006[0-9a-f]+)u', ln)
            if m:
                vas.append(int(m.group(1), 16))
    return sorted(set(vas))


def main(argv):
    exe = argv[1] if len(argv) > 1 else "vendor/unpacked/sotes.unpacked.exe"
    data = open(exe, "rb").read()

    tables = []
    for va in data_set_vas():
        src_pool, pairs = parse_table(data, va)
        if src_pool == 0:                       # within-palette (NPC) — handled
            continue                            # by the pixel-index remap path
        # Every observed cross-slot table is a CONTIGUOUS IDENTITY copy
        # (dst == src over a run [lo,hi]).  Assert it so a future non-identity
        # table fails loudly here instead of being silently mis-emitted as a
        # range — at which point this extractor + the C consumer want a
        # general (dst,src)-pair form (FUN_00417bc0 supports it).
        lo = pairs[0][1]
        for k, (d, s) in enumerate(pairs):
            assert d == s, f"0x{va:08x}: non-identity pair {(d, s)} — needs pair form"
            assert s == lo + k, f"0x{va:08x}: non-contiguous src {s} at {k} — needs pair form"
        hi = pairs[-1][1]
        tables.append((va, src_pool, lo, hi))

    print("/* info_palette_swap_tables_data — GENERATED by")
    print(" * tools/extract/info_palette_swap_tables.py.  DO NOT EDIT BY HAND. */")
    print("/* The CROSS-SLOT palette-swap tables (FUN_00417bc0, info-entry +8 with the")
    print(" * table's first u16 != 0) the port's group3 DATA_SET events reference.  Each")
    print(" * REPLACES this bank's palette entries [lo,hi] with the SAME-index entries of")
    print(" * the slot whose pool index == src_pool (ar_pool_get_slot).  The errands floor")
    print(" * (0x00675500 <- pool 0x186 = res 0x76b) is the per-room grey-floor swap: the")
    print(" * town floor PIXELS (res 0x769/0x76a) slice against res 0x76b's cooler palette.")
    print(" * All observed tables are contiguous identity copies (dst==src over [lo,hi]);")
    print(" * see docs/findings/errands-render-gaps.md §3. */")
    print("static const struct ar_pal_swap_table AR_PAL_SWAP_TABLES[] = {")
    print("  /*  rdata_va,     src_pool, lo,  hi   */")
    for va, src_pool, lo, hi in tables:
        print(f"  {{ 0x{va:08x}u, 0x{src_pool:04x}u, {lo:3d}, {hi:3d} }},")
    print("};")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
