#!/usr/bin/env python3
"""tools/extract/npc_palette_remap.py — extract the NPC colour-variant palette
INDEX-REMAP tables from the retail EXE's .rdata.

The town NPC colour variants (the "Woman"/"Man"/etc. archetypes, e.g. 0xc440)
clone the base 8bpp sprite bank and attach a palette-index-remap table via the
info-entry +8 field (FUN_0057ca40, e.g. `*(info[0xa6]+8) = &DAT_006748d0`).  The
3 shared variant tables live in .rdata at:
    variant 1  DAT_006748d0
    variant 2  DAT_00674ad8
    variant 3  DAT_00674ce0
Each is 520 bytes = TWO parallel 256-byte arrays (half1 @ +0x000, half2 @ +0x100):
half1[k] = the SOURCE palette index, half2[k] = the DEST palette index.  So the
flat per-variant remap is `remap[half1[k]] = half2[k]` for every k where
half1[k] != 0 (identity elsewhere).  Empirically half1 = 0x20..0x4f and half2 =
0x50..0x7f / 0x80..0xaf / 0xb0..0xdf, i.e. the variant shifts the body indices
by +0x30 * v into the next palette colour bank (the 8bpp sheet's embedded palette
holds all four 48-colour banks; the base param_11=0 uses 0x20-0x4f directly).

This is RE'd structural data copied out of the user's own sotes.exe .rdata (the
`world_tables_data.c` pattern), NOT a redistributed asset — re-run against your
own unpacked exe.

Usage:
    nix develop --command python3 tools/extract/npc_palette_remap.py \\
        [vendor/unpacked/sotes.unpacked.exe]   # emits C to stdout
"""
import sys

# .rdata: VMA 0x5cc000, file offset 0x1cc000 (objdump -h of the unpacked exe).
RDATA_VMA = 0x5cc000
RDATA_FOFF = 0x1cc000
TABLES = [(1, 0x006748d0), (2, 0x00674ad8), (3, 0x006748d0 + 2 * 0x208)]  # ce0


def va_to_off(va):
    return RDATA_FOFF + (va - RDATA_VMA)


def build_remap(data, va):
    t = data[va_to_off(va):va_to_off(va) + 0x208]   # 520 bytes
    half1, half2 = t[0x000:0x100], t[0x100:0x200]
    remap = bytearray(range(256))                    # identity default
    for k in range(256):
        if half1[k] != 0:
            remap[half1[k]] = half2[k]
    return remap


def main(argv):
    exe = argv[1] if len(argv) > 1 else "vendor/unpacked/sotes.unpacked.exe"
    data = open(exe, "rb").read()
    print("/* npc_palette_remap_data — GENERATED by "
          "tools/extract/npc_palette_remap.py.  DO NOT EDIT BY HAND. */")
    print("/* The 3 shared NPC colour-variant palette-index remaps, copied out of")
    print(" * the retail EXE's .rdata (DAT_006748d0/ad8/ce0).  remap[old]=new; the")
    print(" * variant shifts body palette indices 0x20-0x4f into the next colour")
    print(" * bank.  Keyed by the retail .rdata VA the info-entry +8 holds. */")
    print("static const struct { unsigned int rdata_va; unsigned char map[256]; }")
    print("NPC_PALETTE_REMAPS[] = {")
    for v, va in TABLES:
        remap = build_remap(data, va)
        body = ",".join(str(b) for b in remap)
        print(f"  {{ 0x{va:08x}u, {{ {body} }} }},  /* variant {v} */")
    print("};")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
