#!/usr/bin/env python3
"""Emit src/portrait_face_data.{c,h} from the retail dialogue-portrait face
table DAT_006b6568 in the user's sotes.exe.

The in-game dialogue-line setup 0x49d6e0 resolves the per-speaker PORTRAIT
bust by scanning this table (0x6b6568, 0x10-byte stride, zero-terminated) for
the record whose key matches (speaker actor head-state +0x1d8, face_id param_8),
then writes one of the record's 3 portrait pool-slot VARIANTS to the dialogue
box +0x84:
  +0x08 (var A) when the speaker body faces 3 (local_110 == 3),
  +0x0a (var B) the default path,
  +0x0c (var C) the bVar4 box-state path (in_ECX+0x2f0 != 0 && +0x7c in {0,1,2,4}).
The render then blits (&DAT_008a760c)[slot] (= the port's g_ar_sprite_slots[slot]).

Only the RE'd mapping (head/face -> portrait slots) is emitted, never asset
bytes — the same precedent as tools/extract/game_world_tables.py (the room/area
registry).  Pure stdlib PE parse; run inside `nix develop` (python3).

Usage: python3 tools/extract/portrait_face_table.py [path-to-unpacked-exe]
       (writes src/portrait_face_data.c and .h)
"""
import struct
import sys

TABLE_VA = 0x6B6568
STRIDE = 0x10


def va_to_off(d, va):
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    coff = pe + 4
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    base = struct.unpack_from("<I", d, coff + 20 + 28)[0]
    sec = coff + 20 + optsz
    rva = va - base
    for i in range(nsec):
        o = sec + i * 40
        vsz, sva, rsz, roff = struct.unpack_from("<IIII", d, o + 8)
        if sva <= rva < sva + max(vsz, rsz):
            return roff + (rva - sva)
    raise ValueError("VA 0x%x not in any section" % va)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "vendor/unpacked/sotes.unpacked.exe"
    d = open(path, "rb").read()
    off = va_to_off(d, TABLE_VA)
    recs = []
    for i in range(1024):
        rec = d[off + i * STRIDE: off + i * STRIDE + STRIDE]
        head, face = struct.unpack_from("<ii", rec, 0)
        if head == 0 and face == 0:
            break
        a, b, c, _ = struct.unpack_from("<HHHH", rec, 8)
        recs.append((head, face, a, b, c))

    h = '''/* portrait_face_data.h — see portrait_face_data.c (GENERATED). */
#ifndef OPENSUMMONERS_PORTRAIT_FACE_DATA_H
#define OPENSUMMONERS_PORTRAIT_FACE_DATA_H
#include <stdint.h>
/* One face-table record (retail DAT_006b6568, stride 0x10): the (head_state,
 * face_id) key + the 3 portrait-slot variants the 0x49d6e0 resolver picks among
 * by the speaker's anim-state (var_a=+0x8 when body facing==3, var_b=+0xa the
 * default, var_c=+0xc the bVar4 box-state path). */
typedef struct portrait_face_rec {
    int32_t  head;    /* speaker actor +0x1d8 head-state (key dword[0])   */
    int32_t  face;    /* face_id (0x49d6e0 param_8; key dword[1])         */
    uint16_t var_a;   /* +0x08 portrait slot (anim-state facing==3)       */
    uint16_t var_b;   /* +0x0a portrait slot (the default path)           */
    uint16_t var_c;   /* +0x0c portrait slot (the bVar4 box-state path)   */
} portrait_face_rec;
const portrait_face_rec *portrait_face_table(int *n);
#endif
'''
    open("src/portrait_face_data.h", "w").write(h)

    lines = [
        '/* portrait_face_data.c — GENERATED by tools/extract/portrait_face_table.py',
        ' *   (portrait_face_table.py [unpacked-exe]).  DO NOT EDIT BY HAND.  The',
        ' *   in-game engine\'s compiled-in dialogue-portrait lookup DAT_006b6568,',
        ' *   copied verbatim out of the retail EXE .rdata @ 0x6b6568 (0x10-byte',
        ' *   stride, zero-terminated).  Only the RE\'d head/face -> portrait-slot',
        ' *   mapping is committed, never asset bytes.  0x49d6e0 keys on',
        ' *   (speaker head-state +0x1d8, face_id) and picks a variant by anim-state.',
        ' *   See portrait.{c,h}. */',
        '#include "portrait_face_data.h"',
        '',
        'static const portrait_face_rec FACE_TABLE[] = {',
    ]
    for hd, f, a, b, c in recs:
        lines.append(f'    {{ {hd}, {f:#06x}, {a}, {b}, {c} }},')
    lines += [
        '};',
        '#define FACE_TABLE_COUNT ((int)(sizeof(FACE_TABLE)/sizeof(FACE_TABLE[0])))',
        '',
        'const portrait_face_rec *portrait_face_table(int *n)',
        '{',
        '    if (n) *n = FACE_TABLE_COUNT;',
        '    return FACE_TABLE;',
        '}',
        '',
    ]
    open("src/portrait_face_data.c", "w").write("\n".join(lines))
    print("wrote src/portrait_face_data.{c,h} with %d records" % len(recs))


if __name__ == "__main__":
    main()
