/*
 * tests/test_main.c — unit-test driver for OpenSummoners ports.
 *
 *   make -C tests run             # all tests
 *   ./tests/build/run_tests       # invoke directly (after first build)
 *
 * Outcomes: 0 pass, 1 fail (with message), 2 skip.  Process exit is 0
 * iff failure count is 0.  Skips don't count as failures.
 *
 * Registration: add one X(name) line to TESTS for every test.  The
 * X-macro expands twice — once for the extern decl, once for the
 * dispatch table — so the test name appears exactly once and can't
 * drift from the declaration.
 */
#include "t.h"

typedef int (*test_fn)(void);

struct test_case {
    const char *name;
    test_fn     fn;
};

/* ─── test registry ───────────────────────────────────────────────────
 * One X(n) per test.  Grouped by ported module for readability.
 */
#define TESTS \
    X(pd_channel_mask_to_shift_rgb565_R)                       \
    X(pd_channel_mask_to_shift_rgb565_G)                       \
    X(pd_channel_mask_to_shift_rgb565_B)                       \
    X(pd_channel_mask_to_shift_rgb555)                         \
    X(pd_channel_mask_to_shift_zero_mask)                      \
    X(pd_channel_mask_to_shift_single_bit_at_0)                \
    X(pd_channel_init_zeroes_and_seeds_weight)                 \
    X(pd_channel_free_lut_when_allocated)                      \
    X(pd_channel_free_lut_when_not_allocated)                  \
    X(pd_blend_init_zeroes_state_and_inits_channels)           \
    X(pd_blend_set_color_writes_per_channel_weights)           \
    X(pd_blend_set_color_does_not_touch_other_fields)          \
    X(pd_blend_layout_matches_retail_offsets)                  \
    X(pd_lut_shared_short_circuit)                             \
    X(pd_lut_different_weight_allocates_fresh)                 \
    X(pd_lut_invalid_state_is_noop)                            \
    X(pd_lut_small_identity_weight_1000)                       \
    X(pd_lut_small_half_weight_500)                            \
    X(pd_lut_small_zero_weight)                                \
    X(pd_lut_small_invert)                                     \
    X(pd_lut_large_mode1_add)                                  \
    X(pd_lut_large_mode2_sub)                                  \
    X(pd_lut_large_default_mode)                               \
    X(pd_format_get_masks_reads_struct)                        \
    X(pd_commit_null_fmt_uses_rgb565_defaults)                 \
    X(pd_commit_custom_format)                                 \
    X(pd_commit_flag_forces_state_2)                           \
    X(pd_commit_nondefault_weight_state_1)                     \
    X(pd_commit_nondefault_mode_state_1)                       \
    X(pd_commit_idempotent_frees_old_luts)                     \
    X(pd_commit_b_uses_r_as_prev_not_g)                        \
    X(pd_boot_group_a_weight_ramp_and_mode)                    \
    X(pd_boot_group_b_weight_ramp_div_22)                      \
    X(pd_boot_group_c_grey_ramp)                               \
    X(pd_boot_group_d_special_colours)                         \
    X(pd_boot_group_e_weight_ramp_and_mode)                    \
    X(pd_boot_all_slots_committed_against_fmt)                 \
    X(pd_boot_custom_fmt_propagates)                           \
    X(pd_boot_init_is_idempotent)                              \
    X(ar_xfree_null_safe)                                      \
    X(ar_color_lerp_endpoints)                                 \
    X(ar_color_lerp_midpoint)                                  \
    X(ar_color_lerp_descending)                                \
    X(ar_color_lerp_ignores_alpha)                             \
    X(palette_pack_entry_basic)                                \
    X(palette_pack_entry_ignores_top_byte)                     \
    X(palette_pack_entry_overwrites_existing)                  \
    X(palette_install_lazy_allocates_first_time)               \
    X(palette_install_reuses_existing_buffer)                  \
    X(palette_install_destroy_frees_buffer)                    \
    X(sprite_destroy_frees_aux_and_entries)                    \
    X(sprite_destroy_safe_on_zero_slot)                        \
    X(sprite_register_writes_all_named_fields)                 \
    X(sprite_register_frees_existing_aux_and_entries)          \
    X(sprite_register_truncates_id_and_group_to_uint16)        \
    X(sprite_register_matches_FUN_005748c0_arg_shape)          \
    X(sprite_clone_copies_all_metadata)                        \
    X(sprite_clone_frees_dst_existing_aux_and_entries)         \
    X(sprite_clone_deep_copies_aux_buf)                        \
    X(sprite_clone_no_aux_when_src_aux_null)                   \
    X(sprite_clone_resets_dst_id_and_group_to_uint16)          \
    X(info_entry_clear_zeroes_marker_flag_data_palette)        \
    X(info_entry_clear_leaves_pad_untouched)                   \
    X(info_entry_pool_wired_by_state_init)                     \
    X(gdi_destroy_deletes_each_handle)                         \
    X(gdi_reset_clears_then_allocates)                         \
    X(make_font_family_courier)                                \
    X(make_font_family_times)                                  \
    X(make_font_family_arial)                                  \
    X(make_font_family_courier_italic)                         \
    X(make_font_unknown_family_skips_face)                     \
    X(set_font_writes_slot_and_handle)                         \
    X(set_font_destroys_existing)                              \
    X(set_pen_bumps_count)                                     \
    X(set_brush_bumps_count)                                   \
    X(set_pen_capacity_zero_no_op)                             \
    X(pen_gradient_endpoints_and_lerp)                         \
    X(pen_gradient_capacity_two)                               \
    X(pen_gradient_capacity_one)                               \
    X(register_fonts_sprite_slots)                             \
    X(register_fonts_gdi_indices)                              \
    X(register_fonts_dimensions_in_call_order)                 \
    X(sound_slot_init_writes_fields)                           \
    X(sound_slot_init_clears_state)                            \
    X(register_sounds_all_ids_and_kinds)                       \
    X(register_sounds_buffer_pointer_preserved)                \
    X(main_sprites_inline_slots_field_map)                     \
    X(main_sprites_transient_idx0_uses_sotesp_module)          \
    X(main_sprites_trailing_ids_in_index_order)                \
    X(main_sprites_untouched_indices_stay_zero)                \
    X(main_sprites_total_slot_count)                           \
    X(main_sprites_coexists_with_register_fonts)               \
    X(game_sprites_inline_block_field_map)                     \
    X(game_sprites_trailing_call_shapes)                       \
    X(game_sprites_total_slot_count)                           \
    X(game_sprites_resource_ids_unique)                        \
    X(game_sprites_untouched_indices_stay_zero)                \
    X(game_sprites_coexists_with_main_sprites)                 \
    X(game_sounds_total_entry_count)                           \
    X(game_sounds_index_range_and_gaps)                        \
    X(game_sounds_field_writes_spot_check)                     \
    X(game_sounds_resource_ids_unique)                         \
    X(game_sounds_coexists_with_main_sounds)                   \
    X(game_sounds_buffer_pointer_preserved)                    \
    X(aux_sounds_writes_four_entries)                          \
    X(aux_sounds_fills_game_sounds_gap)                        \
    X(aux_sounds_buffer_pointer_preserved)                     \
    X(locale_sounds_no_locale_uses_fallback_or_settings)       \
    X(locale_sounds_skip_when_primary_id_zero)                 \
    X(locale_sounds_launcher_flag_forces_fallback)             \
    X(locale_sounds_override_path_uses_current_locale)         \
    X(locale_sounds_override_7fff_skips_under_locale)          \
    X(locale_sounds_coexists_with_game_sounds)                 \
    X(locale_sounds_buffer_pointer_preserved)                  \
    X(group3_sprites_writes_233_distinct_slots)                \
    X(group3_sprites_group_tag_stamped)                        \
    X(group3_sprites_zdd_and_settings_uniform)                 \
    X(group3_sprites_spotcheck_first_entry)                    \
    X(group3_sprites_spotcheck_max_idx)                        \
    X(group3_sprites_spotcheck_colorkey_entry)                 \
    X(group3_sprites_no_overlap_with_main_sprite_indices)      \
    X(group3_info_events_first_event_flag_set)                 \
    X(group3_info_events_marker_and_flag_pair)                 \
    X(group3_info_events_data_ptr_set)                         \
    X(group3_info_events_marker_set_with_high_value)           \
    X(group3_info_events_copy_marker_and_flag_chain)           \
    X(group3_info_events_struct_copy_from_zero_init)           \
    X(group3_info_events_dst_indices_in_92_to_437_range)       \
    X(group3_info_events_fires_from_register_group3_sprites)   \
    X(pool_get_slot_sentinel_returns_null)                     \
    X(pool_get_slot_ramp_range)                                \
    X(pool_get_slot_main_range)                                \
    X(ss_mgr_clone_copies_slot_metadata)                       \
    X(ss_mgr_clone_copies_info_marker_and_flag)                \
    X(ss_mgr_clone_clears_dst_info_data_and_palette)           \
    X(ss_mgr_clone_destroys_old_dst_entries)                   \
    X(group3_clones_apply_is_idempotent)                       \
    X(group3_clones_dst_pool_range)                            \
    X(group3_clones_first_entry_propagates_resource_id)        \
    X(group3_clones_fires_from_register_group3_sprites)        \
    X(inline_clones_targets_populated_after_register)          \
    X(inline_clones_propagate_source_metadata)                 \
    X(inline_clones_late_cluster_shares_one_source)            \
    X(inline_clones_apply_is_idempotent)                       \
    X(inline_clones_src_dst_sets_disjoint)                     \
    X(boot_register_all_group_tags_per_batch)                  \
    X(boot_register_all_zdd_vs_zds_routing)                    \
    X(boot_register_all_sotesp_module_for_special_slots)       \
    X(boot_register_all_locale_state_routed)                   \
    X(boot_register_all_null_locale_skips_tail)                \
    X(boot_register_all_touches_every_batch_signature_slot)    \
    X(ar_layout_matches_retail)                                \
    X(ar_sprite_frame_null_slot_and_entries_return_null)       \
    X(ar_sprite_frame_loaded_indexes_without_hook)             \
    X(ar_sprite_frame_lazy_decode_fires_once_then_indexes)     \
    X(ar_sprite_frame_unloaded_no_hook_returns_null)           \
    X(sheet_decode_pixels_brightness_and_key)                  \
    X(sheet_decode_pixels_truncates_toward_zero)               \
    X(sheet_decode_pixels_lut_then_scale)                      \
    X(sheet_decode_pixels_non24_is_noop)                       \
    X(sheet_decode_pixels_null_pixels_is_noop)                 \
    X(sprite_slice_geometry_and_order)                         \
    X(sprite_slice_default_cell_is_whole_sheet)                \
    X(sprite_slice_count_zero_when_cell_exceeds_sheet)         \
    X(sprite_slice_colorkey_sentinel_passthrough)              \
    X(sprite_slice_null_surface_marks_failure)                 \
    X(sprite_decode_cleanup_then_bs_failure)                   \
    X(sprite_decode_end_to_end_24bpp)                          \
    X(bs_release_no_free_nulls_pixels)                         \
    X(bs_release_is_idempotent_on_null)                        \
    X(bs_release_frees_pixels)                                 \
    X(bs_get_set_bit_count_recomputes_stride)                  \
    X(bs_init_bitmap_stamps_BIH)                               \
    X(bs_init_bitmap_24bpp_size)                               \
    X(bs_emit_palette_bgra_swaps_RGB_to_BGR)                   \
    X(decode_returns_zero_on_missing_resource)                 \
    X(decode_raw_8bpp_copies_palette_and_pixels)               \
    X(decode_raw_24bpp_skips_palette_copy)                     \
    X(decode_raw_unsupported_depth_releases_pixels)            \
    X(compressed_header_signature_mismatch_returns_zero)       \
    X(compressed_header_pixel_offset_too_large)                \
    X(compressed_header_happy_path)                            \
    X(decode_compressed_path_8bpp)                             \
    X(decode_compressed_signature_mismatch_returns_zero)       \
    X(palette_session_begin_emits_BGRA_on_8bpp)                \
    X(palette_session_begin_returns_false_on_missing_resource) \
    X(palette_session_begin_returns_false_on_24bpp)            \
    X(main_sprites_installs_palette_when_resource_8bpp)        \
    X(main_sprites_skips_palette_when_resource_missing)        \
    X(palette_ramps_installs_palettes_on_all_12_slots)         \
    X(palette_ramps_ramp0_three_color_overrides)               \
    X(palette_ramps_ramp4_uses_blue_bg)                        \
    X(palette_ramps_skip_install_when_resource_missing)        \
    X(palette_ramps_ramp_slot_field_writes)                    \
    X(palette_ramps_extras_use_caller_settings)                \
    X(palette_ramps_portrait_flags_written_per_register)       \
    X(palette_ramps_portrait_slot_field_writes)                \
    X(palette_ramps_coexist_with_main_pool_unwritten)          \
    X(trim_24bpp_loose_ybottom_quirk)                          \
    X(trim_8bpp_tight_ybottom)                                 \
    X(trim_all_key_no_opaque)                                  \
    X(trim_all_opaque_no_key)                                  \
    X(trim_other_depth_full_rect)                              \
    X(trim_subwindow_8bpp)                                     \
    X(trim_8bpp_nonsquare_quirk69)                             \
    X(convert_24bpp_to_16bpp_rgb565)                           \
    X(convert_8bpp_to_16bpp_palette_and_key)                   \
    X(convert_to_16bpp_wrong_depth_noop)                       \
    X(convert_8bpp_to_24bpp_expands)                           \
    X(convert_24bpp_to_32bpp_widens)                           \
    X(convert_24bpp_to_32bpp_wrong_depth_noop)                 \
    X(load_palette_from_reverses_channels)                     \
    X(bitmap_session_layout_matches_retail)                    \
    X(wp_harmless_messages_consumed)                           \
    X(wp_close_calls_exit_zero)                                \
    X(wp_default_forwards_to_defwindowproc)                    \
    X(wp_paint_no_ctx_falls_through)                           \
    X(wp_paint_ctx_but_no_paint_this_falls_through)            \
    X(wp_paint_helper_returns_zero_falls_through)              \
    X(wp_paint_consumed_no_defwindowproc)                      \
    X(wp_activateapp_writes_flag_without_ctx)                  \
    X(wp_activateapp_loaded_zero_skips_body)                   \
    X(wp_activateapp_deactivate_calls_pause)                   \
    X(wp_activateapp_activate_minimal_emits_cp3_and_post)      \
    X(wp_activateapp_full_chain_call_order)                    \
    X(wp_activateapp_quiet_suppresses_logs_only)               \
    X(wp_activateapp_extra_null_sparse_loop)                   \
    X(wp_activateapp_device_chain_sets_zdm_active)             \
    X(wp_activateapp_device_chain_partial_zdm_inactive)        \
    X(wp_activateapp_null_zdm_skips_zdm_call)                  \
    X(wp_timer_clears_pump_throttle)                           \
    X(wp_timer_no_ctx_consumed)                                \
    X(wp_state_init_clears_all_globals)                        \
    X(app_ctx_layout_matches_retail)                           \
    X(app_pump_state_init_clears_globals)                      \
    X(app_pump_exits_when_active_and_throttle_clear)           \
    X(app_pump_waits_until_active)                             \
    X(app_pump_waits_until_throttle_clears)                    \
    X(app_pump_wm_quit_calls_exit_no_dispatch)                 \
    X(app_pump_drains_queue_then_exits)                        \
    X(app_pump_wm_quit_stops_drain_immediately)                \
    X(app_pump_limiter_first_frame_sets_throttle)              \
    X(app_pump_limiter_holds_throttle_when_clock_static)       \
    X(app_pump_limiter_skips_throttle_when_clock_advanced)     \
    X(app_pump_limiter_boundary_prev_minus_now_equals_5)       \
    X(app_pump_limiter_boundary_prev_minus_now_equals_4)       \
    X(app_pump_limiter_disabled_no_tick_reads)                 \
    X(app_pump_null_ctx_does_not_crash)                        \
    X(app_pump_drain_then_limiter_first_frame)                 \
    X(title_fade_init_zeroes)                                  \
    X(title_phase0_ramps_by_20_to_1000)                        \
    X(title_phase0_clamps_at_1000)                             \
    X(title_phase1_holds_50_then_advances)                     \
    X(title_phase2_fades_out_and_fires_segment_once)           \
    X(title_phase2_fade_out_saturates_at_zero)                 \
    X(title_phase3_ramps_by_10_to_1000)                        \
    X(title_phase4_holds_20_then_resets_fade)                  \
    X(title_phase5_fade_caps_then_tick_bound_advance)          \
    X(title_phase6_holds_120_then_phase7)                      \
    X(title_phase7_spawns_sparkles_below_850)                  \
    X(title_phase7_holds_90_then_menu)                         \
    X(title_phase7_fade_clamps_at_1000)                        \
    X(title_phase8_returns_menu_and_ramps_fade_first)          \
    X(title_phase9_fades_menu_down_then_back_to_8)             \
    X(title_phase9_menu_fade_saturates_at_zero)                \
    X(title_phase10_fades_out_then_exits)                      \
    X(title_phase10_exit_when_already_zero)                    \
    X(title_full_intro_walk_to_menu)                           \
    X(title_pace_init)                                         \
    X(title_pace_first_frame_pumps_then_updates)               \
    X(title_pace_update_burns_slice_then_renders)              \
    X(title_pace_update_stays_updating_when_budget_high)       \
    X(title_pace_update_realtime_outran_budget_renders)        \
    X(title_pace_update_boundary_elapsed_equals_budget)        \
    X(title_pace_render_refills_and_enters_update)             \
    X(title_pace_render_stays_render_when_budget_small)        \
    X(title_pace_render_clamps_budget_to_100)                  \
    X(title_pace_render_boundary_budget_exactly_16)            \
    X(title_pace_frozen_clock_walk)                            \
    X(title_pace_clock_jump_reenters_update)                   \
    X(title_menu_spawn_builds_five_rows)                       \
    X(title_menu_spawn_cursor_seeks_match)                     \
    X(title_menu_spawn_no_match_keeps_cursor_zero)             \
    X(title_menu_teardown_clears_active_flag)                  \
    X(title_menu_teardown_noop_when_unset)                     \
    X(menu_input_nav_plays_move_sfx)                           \
    X(menu_input_page_button_is_noop)                          \
    X(menu_input_commit_enabled_row)                           \
    X(menu_input_commit_disabled_row)                          \
    X(menu_input_commit_savedata_match)                        \
    X(menu_input_commit_savedata_skipped_for_0x1d)             \
    X(menu_input_idle_frame_no_effects)                        \
    X(menu_input_axis_held_synthesises_move)                   \
    X(menu_input_watchdog_forces_phase10)                      \
    X(title_fade_ramp_index_and_clamp)                         \
    X(title_render_prologue_reset_clear_skip)                  \
    X(title_render_logo_as_sprite_level)                       \
    X(title_render_pressbtn_asset_pairs)                       \
    X(title_render_sparkle_trail)                              \
    X(title_render_menu_bg_and_cursor)                         \
    X(title_render_fadeout)                                    \
    X(title_render_flip_log_once)                              \
    X(title_render_no_sink_is_safe)                            \
    X(rng_matches_msvc_stream)                                 \
    X(rng_srand_is_reproducible)                               \
    X(particle_pool_init)                                      \
    X(particle_spawn_title_fields_and_order)                   \
    X(particle_spawn_appends_sequentially)                     \
    X(particle_spawn_caps_at_capacity)                         \
    X(particle_spawn_x_sweeps_with_intensity)                  \
    X(particle_update_rises_and_accelerates)                   \
    X(particle_update_culls_at_lifetime_end)                   \
    X(particle_update_cull_swaps_last_into_slot)               \
    X(title_scene_init_zeroes_and_binds)                       \
    X(title_scene_render_iteration_presents)                   \
    X(title_scene_abort_poll_returns_6)                        \
    X(title_scene_skip_splash_jumps_to_menu)                   \
    X(title_scene_skip_splash_fires_bgm_cue)                   \
    X(title_scene_skip_splash_phase0_gate)                     \
    X(title_scene_skip_splash_noop_without_press)              \
    X(title_scene_intro_walks_to_menu)                         \
    X(title_scene_watchdog_forces_exit)                        \
    X(title_scene_menu_commit_exits_with_action)               \
    X(title_scene_null_hooks_safe)                             \
    X(sink_unbound_is_noop)                                    \
    X(sink_null_primary_is_noop)                               \
    X(sink_surface_reset_no_blit)                              \
    X(sink_surface_clear_blits_frame)                          \
    X(sink_sprite_resolves_frame_id)                           \
    X(sink_sprite_unregistered_bank_noop)                      \
    X(sink_sprite_level_plain_path)                            \
    X(sink_sprite_level_alpha_path)                            \
    X(sink_frame_end_composes_group)                           \
    X(sink_flip_and_log_callbacks)                             \
    X(sink_logo_op_routes_to_callback)                         \
    X(sink_sparkle_opaque_clipped_when_no_ramp)                \
    X(sink_sparkle_alpha_via_ramp)                             \
    X(sink_menu_cursor_draws_via_ramp)                         \
    X(sink_deferred_null_callbacks_safe)                       \
    X(input_mgr_ring_offsets)                                  \
    X(input_poll_hit_consumes)                                 \
    X(input_poll_wrong_id_misses)                              \
    X(input_poll_flag_must_be_one)                             \
    X(input_poll_age_boundary)                                 \
    X(input_poll_future_ts_rejected)                           \
    X(input_poll_rollover_within_window)                       \
    X(input_poll_highest_index_wins)                           \
    X(input_poll_endpoints_in_range)                           \
    X(input_poll_empty_ring_misses)                            \
    X(input_any_fresh_press_matches_any_id)                    \
    X(input_any_fresh_press_empty_misses)                      \
    X(input_any_fresh_press_flag_and_age)                      \
    X(input_mgr_reset_flushes)                                 \
    X(pool_acquire_stamps_and_bumps)                           \
    X(pool_acquire_index_is_16bit_write)                       \
    X(pool_acquire_exhausts_returns_null)                      \
    X(pool_acquire_zero_capacity_is_null)                      \
    X(sel_mark_last_selects_only_last)                         \
    X(sel_mark_last_single_entry)                              \
    X(sel_mark_last_empty_is_noop)                             \
    X(sel_mark_last_reselects_new_tail)                        \
    X(menu_scroll_recomputes_page_top)                         \
    X(menu_scroll_noop_when_in_view)                           \
    X(menu_scroll_moves_back_up)                               \
    X(menu_scroll_stride_one_tracks_cursor)                    \
    X(menu_scroll_boundary_cursor)                             \
    X(menu_scroll_cursor_zero)                                 \
    X(nav_t0_prev_decrements)                                  \
    X(nav_t0_prev_wraps_to_page_bottom)                        \
    X(nav_t0_prev_wrap_clamps_to_count)                        \
    X(nav_t0_next_increments)                                  \
    X(nav_t0_next_wraps_to_page_top)                           \
    X(nav_t2_next_within_row)                                  \
    X(nav_t2_next_wraps_in_row)                                \
    X(nav_t2_prev_within_row)                                  \
    X(nav_t2_prev_wraps_to_row_end)                            \
    X(nav_t2_page_down_scrolls)                                \
    X(nav_t2_page_up_scrolls)                                  \
    X(nav_t2_page_up_underflow_clamps)                         \
    X(nav_t3_next_drags_page)                                  \
    X(nav_t3_next_no_scroll)                                   \
    X(nav_t3_next_wraps_to_zero)                               \
    X(nav_t3_prev_wraps_to_tail)                               \
    X(nav_cancel_latches_three)                                \
    X(nav_confirm_latches_four)                                \
    X(nav_dir8_is_noop)                                        \
    X(nav_out_of_range_is_noop)                                \
    X(nav_count_below_two_no_move)                             \
    X(nav_repeat_a_arms_then_idles)                            \
    X(nav_repeat_a_fires_as_next)                              \
    X(nav_repeat_a_reset)                                      \
    X(nav_repeat_b_arms_and_fires_as_prev)                     \
    X(nav_repeat_b_reset)                                      \
    X(latch_gate_blocks_when_not_ready)                        \
    X(latch_gate_blocks_when_disabled)                         \
    X(latch_mode1_forwards_to_nav)                             \
    X(latch_unknown_mode_is_noop)                              \
    X(latch_mode2_sub0_ack_clears_flag18)                      \
    X(latch_mode2_sub0_content_latches_eight)                  \
    X(latch_mode2_sub0_no_flags_returns_zero)                  \
    X(latch_mode2_sub0_out_of_range_returns_zero)              \
    X(latch_mode2_sub1_reveals_all)                            \
    X(latch_mode2_sub1_dismisses_at_cap)                       \
    X(latch_mode2_sub1_blocked_once_dismissed)                 \
    X(build_header_fields)                                     \
    X(build_params_carried)                                    \
    X(build_allocates_zeroed_grid)                             \
    X(build_entries_stamped)                                   \
    X(clear_fresh_is_noop)                                     \
    X(build_rebuild_recycles)                                  \
    X(clear_frees_cell_subobjects)                             \
    X(clear_frees_field164)                                    \
    X(clear_frees_confirm_graph)                               \
    X(finalize_fresh_is_noop)                                  \
    X(finalize_zeroes_obj54)                                   \
    X(finalize_zeroes_and_clamps_obj20)                        \
    X(finalize_skips_when_row_outruns_count)                   \
    X(finalize_invokes_layout_hook_for_obj0)                   \
    X(finalize_iterates_all_cells)                             \
    X(node_build_title_call)                                   \
    X(node_build_copies_config_blob)                           \
    X(node_build_child_display_config)                         \
    X(node_build_rebuild_frees_old_children)                   \
    X(node_build_zero_children)                                \
    X(transition_mode1_ramps_in_to_1000)                       \
    X(transition_mode1_in_clamps_not_overshoot)                \
    X(transition_mode1_ramps_out_to_zero)                      \
    X(transition_skips_inactive_node)                          \
    X(transition_skips_other_modes)                            \
    X(transition_loops_all_entries)                            \
    X(transition_null_and_empty_owner_noop)                    \
    X(zdd_layout_matches_retail_offsets)                       \
    X(zdd_ctor_zeros_struct)                                   \
    X(zdd_dderr_name_known_entries)                            \
    X(zdd_dderr_name_unknown_returns_null)                     \
    X(zdd_log_dderr_format_known_hresult)                      \
    X(zdd_log_dderr_format_empty_prefix1)                      \
    X(zdd_log_dderr_format_unknown_hresult)                    \
    X(zdd_log_dderr_format_null_prefixes_tolerated)            \
    X(zdd_restore_cursor_noop_when_shown)                      \
    X(zdd_restore_cursor_shows_when_hidden)                    \
    X(zdd_release_children_in_order_and_zeros_fields)          \
    X(zdd_release_children_skips_nulls)                        \
    X(zdd_dtor_releases_everything_and_flushes_log)            \
    X(zdd_dtor_quiet_when_clean)                               \
    X(zdd_dtor_open_objects_warns_only)                        \
    X(zdd_dtor_flushes_log_buffer_if_nonempty)                 \
    X(zdd_create_success_path)                                 \
    X(zdd_create_failure_path_tears_down)                      \
    X(zdd_object_layout_matches_retail_offsets)                \
    X(zdd_object_ctor_sets_parent_and_bumps_open_objects)      \
    X(zdd_object_release_pixel_buf_frees_and_clears)           \
    X(zdd_object_release_pixel_buf_noop_when_null)             \
    X(zdd_object_dtor_releases_in_retail_order)                \
    X(zdd_object_dtor_clean_object_noop)                       \
    X(zdd_obj_destroy_walks_dtor_and_frees)                    \
    X(zdd_obj_destroy_idempotent_on_null)                      \
    X(zdd_build_desc_minimal_no_pixelformat)                   \
    X(zdd_build_desc_caps_base_preserved)                      \
    X(zdd_build_desc_force_videomem_adds_caps)                 \
    X(zdd_build_desc_self_videomem_flag_adds_caps)             \
    X(zdd_build_desc_pixelformat_mode_2_8bpp)                  \
    X(zdd_build_desc_pixelformat_mode_2_16bpp_rgb565)          \
    X(zdd_build_desc_pixelformat_mode_2_24bpp)                 \
    X(zdd_build_desc_pixelformat_mode_2_32bpp)                 \
    X(zdd_build_desc_pixelformat_mode_2_unknown_bpp)           \
    X(zdd_build_desc_mode_other_no_pixelformat_even_with_bpp)  \
    X(zdd_object_prefill_stamps_caps_and_force_vm)             \
    X(zdd_object_prefill_stamps_self_pointers)                 \
    X(zdd_object_prefill_zeros_ddsd_and_stamps_dwsize)         \
    X(zdd_object_stamp_metrics_writes_all_slots)               \
    X(zdd_object_stamp_metrics_does_not_touch_other_fields)    \
    X(zdd_object_set_color_key_sentinel_short_circuits)        \
    X(zdd_object_set_color_key_non_sentinel_calls_vtable)      \
    X(zdd_object_set_color_key_16bpp_converts_through_descriptor)\
    X(zdd_object_set_color_key_8bpp_skips_conversion)          \
    X(zdd_object_set_color_key_failure_logs_and_returns_zero)  \
    X(zdd_object_create_surface_pair_happy_path)               \
    X(zdd_object_create_surface_pair_create_surface_fails)     \
    X(zdd_object_create_surface_pair_passes_caps_from_field)   \
    X(zdd_object_create_surface_pair_with_real_colorkey)       \
    X(zdd_object_create_surface_pair_returns_1_on_sentinel_success) \
    X(zdd_object_create_surface_pair_returns_0_on_create_fail) \
    X(zdd_object_create_surface_pair_returns_0_on_setkey_fail) \
    X(zdd_object_new_happy_path)                               \
    X(zdd_object_new_create_failure_cleans_up)                 \
    X(zdd_object_new_setkey_failure_cleans_up)                 \
    X(zdd_object_attach_clipper_call_order)                    \
    X(zdd_object_attach_clipper_releases_existing_com_back)    \
    X(zdd_object_attach_clipper_create_fail_skips_followups)   \
    X(zdd_object_attach_clipper_no_primary_skips_setclipper)   \
    X(zdd_hide_cursor_hides_when_shown)                        \
    X(zdd_hide_cursor_noop_when_already_hidden)                \
    X(zdd_hide_then_restore_round_trip)                        \
    X(zdd_set_display_mode_passes_args_and_returns_one)        \
    X(zdd_set_display_mode_failure_logs_dderr)                 \
    X(zdd_get_display_mode_fills_all_out_ptrs)                 \
    X(zdd_get_display_mode_tolerates_null_out_ptrs)            \
    X(zdd_get_display_mode_failure_leaves_outs_untouched)      \
    X(zdd_busy_wait_ms_records_arg)                            \
    X(zdd_object_attach_backbuffer_happy_path)                 \
    X(zdd_object_attach_backbuffer_force_videomem_sets_caps)   \
    X(zdd_object_attach_backbuffer_failure_returns_zero)       \
    X(zdd_setup_8bit_palette_happy_path)                       \
    X(zdd_setup_8bit_palette_no_primary_skips_set)             \
    X(zdd_setup_8bit_palette_createpalette_failure)            \
    X(zdd_setup_8bit_palette_setpalette_failure)               \
    X(zdd_primary_desc_mode_full_no_vram)                      \
    X(zdd_primary_desc_mode_full_with_vram)                    \
    X(zdd_primary_desc_mode_safe)                              \
    X(zdd_primary_desc_mode_db_ignores_vram)                   \
    X(zdd_primary_desc_mode_zoom)                              \
    X(zdd_create_screen_mode_full_happy_path)                  \
    X(zdd_create_screen_mode_full_with_videomem)               \
    X(zdd_create_screen_mode_safe)                             \
    X(zdd_create_screen_mode_windowed_skips_primary_create)    \
    X(zdd_create_screen_mode_db)                               \
    X(zdd_create_screen_mode_zoom)                             \
    X(zdd_create_screen_8bpp_creates_palette)                  \
    X(zdd_create_screen_primary_create_failure)                \
    X(zdd_create_screen_releases_prior_state)                  \
    X(zdd_object_get_dc_null_self_returns_zero)                \
    X(zdd_object_get_dc_null_com_primary_returns_zero)         \
    X(zdd_object_get_dc_forwards_and_returns_one)              \
    X(zdd_object_get_dc_returns_one_even_when_primitive_fails) \
    X(zdd_object_release_dc_forwards)                          \
    X(zdd_object_release_dc_null_self_noop)                    \
    X(zdd_object_blt_onto_null_self_degenerate_success)        \
    X(zdd_object_blt_onto_null_dest_returns_zero)              \
    X(zdd_object_blt_onto_builds_rects_and_forwards)           \
    X(zdd_present_null_self_noop)                              \
    X(zdd_present_mode_0_full_flips_com_a)                     \
    X(zdd_present_mode_0_skips_when_com_a_null)                \
    X(zdd_present_mode_1_safe_blts_full_rect)                  \
    X(zdd_present_mode_2_windowed_get_blit_release)            \
    X(zdd_present_mode_3_db_blt_then_flip)                     \
    X(zdd_present_mode_4_zoom_blt_then_flip)                   \
    X(zdd_present_default_mode_is_noop)                        \
    X(zdd_window_paint_null_self_returns_zero)                 \
    X(zdd_window_paint_non_mode2_returns_zero_no_calls)        \
    X(zdd_window_paint_null_primary_obj_returns_zero)          \
    X(zdd_window_paint_mode2_full_sequence)                    \
    X(zdd_window_paint_does_not_touch_present_primitives)      \
    X(zdd_object_lock_null_self_returns_zero)                  \
    X(zdd_object_lock_null_com_primary_returns_zero)           \
    X(zdd_object_lock_success_forwards_and_returns_one)        \
    X(zdd_object_lock_failure_logs_and_returns_zero)           \
    X(zdd_object_unlock_null_self_noop)                        \
    X(zdd_object_unlock_forwards_to_primitive)                 \
    X(zdd_object_clear_null_self_noop)                         \
    X(zdd_object_clear_lock_failure_skips_fill_and_unlock)     \
    X(zdd_object_clear_zero_fills_and_unlocks)                 \
    X(zdd_object_clear_zero_size_safe)                         \
    X(zdd_copy_cell_pixels_basic_24bpp)                        \
    X(zdd_copy_cell_pixels_lock_failure_returns_zero)          \
    X(zdd_copy_cell_pixels_clamps_to_dest_pitch)               \
    X(zdd_build_cell_no_trim_creates_and_copies)               \
    X(zdd_build_cell_trim_tightens_box)                        \
    X(zdd_build_cell_found_key_zero_drops_colorkey)            \
    X(zdd_build_cell_fully_transparent_is_metrics_only)        \
    X(zdd_build_cell_create_failure_returns_zero)              \
    X(zdd_new_cell_success_publishes_object)                   \
    X(zdd_new_cell_build_failure_frees_and_returns_zero)       \
    X(zdd_bind_pixel_format_null_self_returns_zero)            \
    X(zdd_bind_pixel_format_null_surface_returns_zero)         \
    X(zdd_bind_pixel_format_getdesc_failure_returns_zero)      \
    X(zdd_bind_pixel_format_rgb565_stamps_descriptor)          \
    X(zdd_bind_pixel_format_rgb555_stamps_descriptor)          \
    X(zdd_color_convert_null_self_returns_zero)                \
    X(zdd_color_convert_rgb565_white)                          \
    X(zdd_color_convert_rgb565_pure_red)                       \
    X(zdd_color_convert_rgb565_pure_blue)                      \
    X(zdd_color_convert_rgb565_mid_gray)                       \
    X(zdd_object_blt_keyed_null_self_degenerate_success)       \
    X(zdd_object_blt_keyed_null_com_primary_degenerate_success)\
    X(zdd_object_blt_keyed_null_dest_returns_zero)             \
    X(zdd_object_blt_keyed_offsets_dest_by_metric_0c_10)       \
    X(zdd_object_upscale_16bpp_null_dest_noop)                 \
    X(zdd_object_upscale_16bpp_null_src_noop)                  \
    X(zdd_object_upscale_16bpp_zero_scale_noop)                \
    X(zdd_object_upscale_16bpp_dest_lock_fail_skips_src)       \
    X(zdd_object_upscale_16bpp_both_locks_then_both_unlocks)   \
    X(zdd_alpha_blit_mode0_identity_copies)                    \
    X(zdd_alpha_blit_colorkey_skips)                           \
    X(zdd_alpha_blit_mode0_lut_transforms_red)                 \
    X(zdd_alpha_blit_mode2_colorize)                           \
    X(zdd_alpha_blit_mode1_blends_with_dest)                   \
    X(zdd_alpha_blit_clips_width_to_dst_stride)                \
    X(zdd_alpha_blit_clips_negative_origin)                    \
    X(zdd_alpha_blit_mode_out_of_range_noop)                   \
    X(zdd_alpha_blit_pixels_null_guards)                       \
    X(zdd_alpha_blit_wrapper_src_lock_fail_noop)               \
    X(zdd_alpha_blit_wrapper_drives_core_and_unlocks)          \
    X(zdd_object_blt_rects_null_src_degenerate_success)        \
    X(zdd_object_blt_rects_null_dest_returns_zero)             \
    X(zdd_object_blt_rects_builds_both_rects_and_forwards)     \
    X(zdd_blit_orchestrate_simple_locks_dest_blits_unlocks)    \
    X(zdd_blit_orchestrate_complex_gdi_roundtrip)              \
    X(zdd_object_is_lost_null_self_returns_zero)               \
    X(zdd_object_is_lost_null_com_primary_returns_zero)        \
    X(zdd_object_is_lost_ddok_returns_zero)                    \
    X(zdd_object_is_lost_surfacelost_returns_one)              \
    X(zdd_object_is_lost_other_hr_returns_zero)                \
    X(zdd_object_restore_surface_null_self_noop)               \
    X(zdd_object_restore_surface_forwards)                     \
    X(zdd_check_any_surface_lost_all_clean_returns_zero)       \
    X(zdd_check_any_surface_lost_com_a_lost_returns_one_early) \
    X(zdd_check_any_surface_lost_back_obj_b_lost)              \
    X(zdd_restore_all_surfaces_hits_every_slot)                \
    X(zdd_restore_all_surfaces_skips_nulls)                    \
    X(cs_compute_zoom_rect_clean_centre)                       \
    X(cs_compute_zoom_rect_exact_match)                        \
    X(cs_compute_zoom_rect_zoom_larger_than_display)           \
    X(cs_compute_zoom_rect_odd_difference_floors)              \
    X(cs_log_append_failure_empty_buffer_overwrites)           \
    X(cs_log_append_failure_appends_with_newline)              \
    X(cs_log_append_failure_null_msg_safe)                     \
    X(cs_dispatch_releases_prior_primary_pair)                 \
    X(cs_dispatch_mode0_full_args_and_pair_alloc)              \
    X(cs_dispatch_mode1_safe_args_and_no_pair)                 \
    X(cs_dispatch_mode2_windowed_args_and_no_preamble)         \
    X(cs_dispatch_mode3_db_args)                               \
    X(cs_dispatch_mode4_zoom_with_override)                    \
    X(cs_dispatch_mode4_zoom_without_override_uses_getdisplaymode) \
    X(cs_dispatch_mode0_createscreen_fail_routes_to_full_string) \
    X(cs_dispatch_mode1_createscreen_fail_routes_to_safe_string) \
    X(cs_dispatch_mode2_createscreen_fail_routes_to_wind_string) \
    X(cs_dispatch_mode3_createscreen_fail_uses_db_lasterror_variant) \
    X(cs_dispatch_mode4_zoom_too_small_aborts)                 \
    X(cs_dispatch_mode4_zoom_exact_match_proceeds)             \
    X(cs_dispatch_default_mode_is_noop)                        \
    X(call_trace_emits_row_for_enabled_frame)                  \
    X(call_trace_frame_whitelist_gates)                        \
    X(call_trace_stub_marker)                                  \
    X(call_trace_disabled_when_no_path)                        \
    X(call_trace_multiple_rows_one_frame)                      \
    X(call_trace_seq_orders_and_resets)                        \
    X(call_trace_field_bearing_payload)                        \
    X(call_trace_field_bearing_stub)                           \
    X(call_trace_field_bearing_empty_and_gated)                \
    X(render_id_register_and_lookup)                           \
    X(render_id_overwrite)                                     \
    X(render_id_forget_and_recycle)                            \
    X(render_id_forget_probes_past_tombstone)                  \
    X(render_id_sheet_hash_table)                              \
    X(render_id_fnv1a_known_vector)                            \
    X(render_id_fnv1a_sensitive_and_seeded)                    \
    X(title_render_resolve_basic)                              \
    X(title_render_resolve_frame_index_min_clamp)              \
    X(title_render_resolve_frame_index_masks_to_u16)           \
    X(title_render_resolve_ramp_clamp_low_high_mid)            \
    X(title_render_resolve_div_zero_is_invalid)                \
    X(title_render_resolve_null_sprite_is_invalid)             \
    X(title_render_resolve_null_entry_is_invalid)              \
    X(title_render_resolve_null_ramp_yields_null_desc)         \
    X(title_render_draw_iterates_and_skips_invalid)            \
    X(title_render_draw_null_and_empty_group_noop)             \
    X(title_render_draw_sprite_plain_keyed)                    \
    X(title_render_level_zero_level_no_draw)                   \
    X(title_render_level_alpha_path)                           \
    X(title_render_level_plain_when_ramp_null_or_past_end)     \
    X(title_render_level_div_nonpos_idx_zero)                  \
    X(title_render_cursor_alpha_and_clamps)                    \
    X(title_render_cursor_guards)                              \
    X(zdd_object_blt_clipped_null_src_degenerate_success)      \
    X(zdd_object_blt_clipped_no_clip_forwards_rects)           \
    X(zdd_object_blt_clipped_left_top_clip)                    \
    X(zdd_object_blt_clipped_clamps_to_extent)                 \
    X(zdd_object_blt_clipped_collapsed_returns_zero)           \
    X(zdd_object_blt_clipped_null_dest_on_live_path_returns_zero) \
    X(title_render_sparkle_alpha_path)                         \
    X(title_render_sparkle_clipped_path)                       \
    X(title_drive_init_allocates_and_binds)                    \
    X(title_drive_step_presents_on_render)                     \
    X(title_drive_step_null_primary_no_present)                \
    X(title_drive_step_abort_returns_done)                     \
    X(title_drive_menu_spawn_then_shutdown_clean)              \
    X(title_drive_shutdown_no_spawn_and_uninit)                \
    X(input_trace_parse_basic)                                 \
    X(input_trace_parse_tolerant)                              \
    X(input_trace_parse_out_of_order_fails)                    \
    X(input_trace_parse_malformed_fails)                       \
    X(input_trace_replay_injects_at_frame)                     \
    X(input_trace_replay_catches_up)                           \
    X(input_trace_replay_guards)                               \
    X(app_flow_dispatch_codes)                                 \
    X(glyph_token_search_found)                                \
    X(glyph_token_search_absent)                               \
    X(glyph_token_search_empty_needle)                         \
    X(glyph_token_search_start_offset)                         \
    X(glyph_token_search_skips_sjis_trail)                     \
    X(glyph_layout_ascii)                                      \
    X(glyph_layout_sjis)                                       \
    X(glyph_layout_lazy_alloc_then_reuse)                      \
    X(glyph_layout_empty_string)                               \
    X(glyph_layout_overlong_drops_text)                        \
    X(glyph_layout_bounds_noop)                                \
    X(glyph_layout_escape_hook_fires)                          \
    X(glyph_row_draw_ascii_advance)                            \
    X(glyph_row_draw_sjis_double_advance)                      \
    X(grid_render_normal_row_shadow_and_text)                  \
    X(grid_render_focused_row_uses_focus_colour)               \
    X(grid_render_disabled_row_no_shadow)                      \
    X(grid_render_two_columns_positions)                       \
    X(grid_render_sel2_and_stride_paging)                      \
    X(grid_render_monospace_right_align)                       \
    X(grid_render_ruby_gate_noop_for_raw_text)                 \
    X(grid_render_empty_cell_skipped)                          \
    X(grid_render_null_list_noop)                              \
    X(newgame_config_matches_retail_stream)                    \
    X(newgame_config_focus_colours)                            \
    X(newgame_config_column_geometry)                          \
    X(newgame_scene_init_focus_and_tooltip)                    \
    X(newgame_scene_nav_moves_cursor)                          \
    X(newgame_scene_dispatch_actions)                          \
    X(newgame_scene_set_option_relays_value)                   \
    X(newgame_drive_init_builds_and_binds)                     \
    X(newgame_drive_step_ramps_gate_and_renders)               \
    X(newgame_drive_nav_gated_then_moves)                      \
    X(newgame_drive_confirm_start_game)                        \
    X(newgame_drive_fadeout_then_start)                        \
    X(newgame_drive_back_returns_to_title)                     \
    X(newgame_drive_confirm_option_opens_picker)               \
    X(newgame_drive_picker_commits_value)                      \
    X(newgame_drive_picker_cancel_keeps_value)                 \
    X(newgame_drive_shutdown_safe)                             \
    X(newgame_box_menu_covers_exactly)                         \
    X(newgame_box_tooltip_covers_exactly)                      \
    X(newgame_box_center_vs_border)                            \
    X(newgame_box_tiny_guard)                                  \
    X(newgame_cursor_frame_cycles)                             \
    X(newgame_cursor_base_row0_golden)                         \
    X(newgame_cursor_row_pitch)                                \
    X(newgame_cursor_render_composes)                          \
    X(glyph_wrap_difficulty_splits_65_52)                      \
    X(glyph_wrap_forced_break_on_percent_n)                    \
    X(glyph_wrap_short_string_one_row)                         \
    X(glyph_wrap_empty_is_zero_rows)                           \
    X(glyph_wrap_bare_percent_n)                               \
    X(glyph_wrap_boundary_is_exact)                            \
    X(picker_values_difficulty_locked)                         \
    X(picker_values_difficulty_unlocked)                       \
    X(picker_values_auto_guard)                                \
    X(picker_values_unported_id_is_empty)                      \
    X(picker_init_seeks_current_value)                         \
    X(picker_init_no_choices_returns_zero)                     \
    X(picker_nav_then_commit)                                  \
    X(picker_back_cancels)                                     \
    X(prologue_init_state)                                     \
    X(prologue_init_caption_stagger)                           \
    X(prologue_start_delay)                                    \
    X(prologue_gem_fade_in_to_hold)                            \
    X(prologue_frame_cadence)                                  \
    X(prologue_gem_frame_wraps)                                \
    X(prologue_rise)                                           \
    X(prologue_caption_wait_then_grow)                         \
    X(prologue_abort)                                          \
    X(prologue_three_beats_begin_exit)                         \
    X(prologue_exit_completes)                                 \
    X(prologue_watchdog_completes)                             \
    X(prologue_render_gated_by_delay)                          \
    X(prologue_render_gem_aura)                                \
    X(prologue_render_gem_alpha_cap)                           \
    X(prologue_render_caption_grid)                            \
    X(prologue_drive_runs_and_renders)                         \
    X(prologue_drive_abort)                                    \
    X(prologue_drive_completes)                                \
    X(game_drive_init)                                         \
    X(game_drive_runs_and_renders)                             \
    X(game_drive_headless)                                     \
    X(game_world_build_counts)                                 \
    X(game_world_first_town_room)                              \
    X(game_world_area_defaults_filled)                         \
    X(game_world_find_room_by_id)                              \
    X(game_world_map_3f2_opening_room)                         \
    X(game_world_header_sentinel)                              \
    X(game_world_reciprocal_exits)                             \
    X(game_map_3f2_room_key)                                   \
    X(game_map_header_fields)                                  \
    X(game_map_actor_slots)                                    \
    X(game_map_tail_pairs)                                     \
    X(game_map_resolves_opening_room)                          \
    X(game_map_zero_defaults_to_3f2)                           \
    X(map_data_header)                                         \
    X(map_data_cells_copied)                                   \
    X(map_data_layers)                                         \
    X(map_data_truncated)                                      \
    X(map_data_cell_fields)                                    \
    X(map_data_cell_bounds)                                    \
    X(map_grid_set_dims)                                       \
    X(map_grid_clear_cell)                                     \
    X(map_grid_emit_obj_block)                                 \
    X(map_grid_emit_obj_clamps_dims)                           \
    X(map_grid_emit_tile_explicit_span)                        \
    X(map_grid_emit_tile_bank_span)                            \
    X(map_decode_1b58b_shape0)                                 \
    X(map_decode_1b58b_shape2)                                 \
    X(map_decode_1b58d_shape2_blend)                           \
    X(map_decode_1b58f_shape0_base_only)                       \
    X(map_decode_1b58f_shape12_fg)                             \
    X(map_decode_29ff4_shape14_z1)                             \
    X(map_decode_single_tile_arms)                             \
    X(map_decode_1b5ab)                                        \
    X(map_decode_full_small)                                   \
    X(map_decode_empty_cell_noop)                              \
    X(map_render_camera_init)                                  \
    X(map_render_camera_town_first_frame)                      \
    X(map_render_window_basic)                                 \
    X(map_render_window_clamps_origin)                         \
    X(map_render_window_no_cap_when_near_edge)                 \
    X(map_render_window_row_sum_components)                    \
    X(map_render_grid_index)                                   \
    X(map_render_tile_basic)                                   \
    X(map_render_tile_empty_cell)                              \
    X(map_render_tile_footprint_suboffset)                     \
    X(map_render_walk_basic)                                   \
    X(map_render_walk_resolver_gate)                           \
    X(map_render_walk_window_clip)                             \
    X(draw_pool_node_size)                                     \
    X(draw_pool_caps_table)                                    \
    X(draw_pool_emit_fields)                                   \
    X(draw_pool_emit_layer_mask)                               \
    X(draw_pool_emit_overflow)                                 \
    X(draw_pool_layer0_always_full)                            \
    X(draw_pool_reset)                                         \
    X(map_present_project_basic)                               \
    X(map_present_project_camera_and_offset)                   \
    X(map_present_project_cull_left)                           \
    X(map_present_project_cull_right_bottom)                   \
    X(map_present_walk_order_and_geometry)                     \
    X(map_present_walk_alpha_kind)                             \
    X(map_present_walk_culls_offscreen)                        \
    X(map_present_walk_defers_other_modes)                     \
    X(map_present_walk_dry_count)                              \
    X(parallax_select_town)                                    \
    X(parallax_select_param3_normalize)                        \
    X(parallax_select_case1_no_b)                              \
    X(parallax_select_a_only_and_default)                      \
    X(parallax_grid_roundtrip)                                 \
    X(parallax_render_zero_camera)                             \
    X(parallax_render_town_first_frame)                        \
    X(parallax_render_dry_and_empty)                           \
    X(town_render_one_tile)                                    \
    X(town_render_resolver_gate)                               \
    X(town_render_empty)                                       \
    X(town_render_dry_step)                                    \
    X(town_render_unloaded_noop)                               \
    X(town_render_malformed)                                   \
    X(town_render_parallax_wired)                              \
    X(color_grade_town_lut_samples)                            \
    X(color_grade_identity)                                    \
    X(color_grade_active_gate)                                 \
    X(color_grade_apply_palette_rgb)                           \
    X(camera_follow_pan_trajectory)                            \
    X(camera_follow_vel_caps_at_speed)                         \
    X(camera_follow_lands_exact_no_overshoot)                  \
    X(camera_follow_far_boost_only_when_flagged)               \
    X(camera_shake_inactive_is_zero)                           \
    X(camera_follow_step_both_axes)                            \
    X(camera_apply_snap_jumps_and_clamps)                      \
    X(camera_apply_pan_sets_target_keeps_cur)                  \
    X(anim_clip_loop_trajectory)                               \
    X(anim_clip_oneshot_holds_last)                            \
    X(anim_clip_duration_gate)                                 \
    X(anim_clip_null_is_noop)                                  \
    X(anim_clip_set_is_change_gated)                           \
    X(anim_clip_sprite_id)                                     \

#define X(n) extern int test_##n(void);
TESTS
#undef X

static const struct test_case TESTS_TABLE[] = {
#define X(n) { #n, test_##n },
    TESTS
#undef X
};
static const size_t N_TESTS = sizeof(TESTS_TABLE) / sizeof(TESTS_TABLE[0]);

int main(int argc, char **argv)
{
    const char *filter = (argc >= 2) ? argv[1] : NULL;
    int pass = 0, fail = 0, skip = 0;

    for (size_t i = 0; i < N_TESTS; i++) {
        const struct test_case *t = &TESTS_TABLE[i];
        if (filter && !strstr(t->name, filter)) continue;
        fprintf(stderr, "[%zu/%zu] %s\n", i + 1, N_TESTS, t->name);
        int rc = t->fn();
        if      (rc == 0) pass++;
        else if (rc == 2) skip++;
        else              fail++;
    }

    fprintf(stderr, "\nresult: %d pass, %d fail, %d skip (of %zu)\n",
            pass, fail, skip, N_TESTS);
    return fail == 0 ? 0 : 1;
}
