#!/usr/bin/env python3
"""Dump the retail character BASE-STAT table DAT_0067ac58 from the user's sotes.exe.

FUN_00426fd0(stats_block, char_code, level) initialises a character's stat block
(member+0x750) by looking this table up on (code, level): it matches the first row
whose code == char_code AND (level == char_level OR char_level == 0), falling back
to row 0.  The freeroam HUD (FUN_00494e60) then reads the resulting block for the
leader panel's HP / MP / level / EXP — so these are pure table lookups, NOT computed
(proven: Arche 0xc35a lvl 1 = HP 100 / MP 20 / EXP-max 250, byte-for-byte).

Row layout (0xdc bytes = 0x37 dwords), the columns FUN_00426fd0 consumes:
  +0x00  u32  character code (key; the list is code==0 terminated; row 0 = fallback)
  +0x04  u32  level          (row[1]  -> stats +0xe0 combat_level_max)
  +0x08  i32  HP             (row[2]  -> stats +0x58 max & +0x54 cur)
  +0x0c  i32  MP             (row[3]  -> stats +0x60 max & +0x5c cur)
  +0x10  i32  stat0..3       (row[4..7] -> stats +0x64/+0x68/+0x6c/+0x70; ATK/DEF/…)
  +0x20  i32  EXP-max        (row[8]  -> stats +0xec)
  +0x3a  char[] name         (ASCII, NUL-term; on the character's level-1 row)
(row[9..13] = other stat-block fields the HUD panel doesn't read; +0x2c row[11] is
the RNG-scaled growth seed -> stats +0xf4.)

Emits the GENERATED src/base_stat_table.c (like portrait_face_data.c): only the
derived RE facts (code/level/HP/MP/stats/EXP + the level-1 name as a comment) are
committed — never asset bytes.  Pure-stdlib PE parse; runs outside nix.

Usage: python3 tools/dump_stat_table.py [path-to-unpacked-exe] > src/base_stat_table.c
  (if python3 lives only in `nix develop` here, strip the shell banner from stdout:
   nix develop --command python3 tools/dump_stat_table.py 2>/dev/null \
     | awk 'f||/^\\/\\*/{f=1;print}' > src/base_stat_table.c)
"""
import struct
import sys

TABLE_VA = 0x67AC58
STRIDE = 0xDC


def va_to_off(d, va):
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    coff = pe + 4
    optsz = struct.unpack_from("<H", d, coff + 16)[0]
    opt = coff + 20
    nsec = struct.unpack_from("<H", d, coff + 2)[0]
    base = struct.unpack_from("<I", d, opt + 28)[0]
    sec = opt + optsz
    rva = va - base
    for i in range(nsec):
        o = sec + i * 40
        vsz, sva, rsz, roff = struct.unpack_from("<IIII", d, o + 8)
        if sva <= rva < sva + max(vsz, rsz):
            return roff + (rva - sva), base
    raise ValueError("VA 0x%x not in any section" % va)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "vendor/unpacked/sotes.unpacked.exe"
    d = open(path, "rb").read()
    off, base = va_to_off(d, TABLE_VA)

    rows = []
    for i in range(4096):
        b = d[off + i * STRIDE:off + i * STRIDE + STRIDE]
        if len(b) < STRIDE:
            break
        dw = struct.unpack_from("<15I", b, 0)
        code = dw[0]
        if code == 0:
            break
        name = b[0x3A:0x3A + 16].split(b"\x00")[0].decode("latin1", "replace")
        # signed for HP/MP/stats/exp
        vals = [struct.unpack_from("<i", b, k * 4)[0] for k in range(9)]
        rows.append((code, vals, name))

    out = sys.stdout.write
    out("/* base_stat_table.c — GENERATED by tools/dump_stat_table.py from the user's\n")
    out(" * own sotes.exe (image base 0x%x, DAT_0067ac58 @ file off 0x%x).  DO NOT EDIT\n" % (base, off))
    out(" * BY HAND — regenerate: python3 tools/dump_stat_table.py > src/base_stat_table.c\n")
    out(" *\n")
    out(" * The retail character base-stat table FUN_00426fd0 reads to fill member+0x750\n")
    out(" * (HP/MP/level/EXP the freeroam HUD leader panel shows).  NUMERIC RE facts only\n")
    out(" * (code/level/HP/MP/stats/EXP); the level-1 NAME is a trailing comment for\n")
    out(" * readability, never embedded as data.  See base_stat_table.h.\n")
    out(" */\n")
    out('#include "base_stat_table.h"\n\n')
    out("#include <stddef.h>\n\n")
    out("const base_stat_row BASE_STAT_TABLE[] = {\n")
    for code, v, name in rows:
        nm = (" /* %s */" % name) if name else ""
        out("    { 0x%05x, %2d, %5d, %4d, { %4d, %4d, %4d, %4d }, %6d },%s\n"
            % (code, v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8], nm))
    out("};\n\n")
    out("const size_t BASE_STAT_TABLE_COUNT =\n")
    out("    sizeof BASE_STAT_TABLE / sizeof BASE_STAT_TABLE[0];\n")


if __name__ == "__main__":
    main()
