/*
 * party.c — see party.h.  The dramatist table DAT_006b6ea8 + the 0x41f200
 * spawn-time handle->code/bank resolution (the chip that makes a NAMED character
 * render its own sheet instead of the archetype's generic townsperson default).
 */
#include "party.h"
#include "base_stat_table.h"

#include <stddef.h>

/*
 * The retail "Get Dramatist Info" table DAT_006b6ea8 (image base 0x400000,
 * file off 0x2b6ea8), generated by tools/dump_dramatist_table.py from the
 * user's own vendor/unpacked/sotes.unpacked.exe.  79 rows, handle==0 terminated
 * in retail (the count is fixed here).
 *
 * NUMERIC RE facts only (handle / code / bank — like every other resolved table
 * in the port, e.g. asset_register.c's resource-id maps).  The character NAMES
 * are story content: they are NOT embedded here — they live in the documentation
 * (docs/proofs/dramatist-table.md) and regenerate from the user's own binary via
 * the dump tool.  The arrival cast this module renders, by handle:
 *   0x05f5e165 Arche (leader, party-loaded)   0x05f5e1d3 Arche's Father (-> 0xe3)
 *   0x05f5e1d4 Arche's Mother (-> 0xb5)        0x35a4e901 Dr. Barnard
 *   0x0c878d35 the Guard
 * Regenerate the rows: tools/dump_dramatist_table.py (then strip the name column).
 */
static const party_dramatist_row DRAMATIST_TABLE[] = {
    { 0x05f5e165, 0x0c35a, 0x000 },  { 0x05f5e166, 0x0c35b, 0x000 },
    { 0x05f5e167, 0x0c35c, 0x000 },  { 0x05f5e168, 0x0c35d, 0x000 },
    { 0x05f5e1d3, 0x0c3dc, 0x0e3 },  { 0x05f5e1d4, 0x0c440, 0x0b5 },
    { 0x35a4e902, 0x0c440, 0x0b4 },  { 0x35a4e903, 0x0c440, 0x0b3 },
    { 0x35a4e904, 0x0c3dc, 0x0e4 },  { 0x35a4e905, 0x0c3f3, 0x0f4 },
    { 0x0c86c9e5, 0x0c3f1, 0x000 },  { 0x0c873f15, 0x0c440, 0x0ab },
    { 0x0c86f0f5, 0x0c440, 0x0a7 },  { 0x0c86a2d5, 0x0c454, 0x0ce },
    { 0x0c878d35, 0x0c3e6, 0x0e6 },  { 0x35a4e901, 0x0c3f0, 0x0ec },
    { 0x0c86c9e6, 0x0c443, 0x000 },  { 0x0db75aa5, 0x0e2a8, 0x000 },
    { 0x35a4e908, 0x0c3be, 0x0d6 },  { 0x35a4e90b, 0x0c42c, 0x09e },
    { 0x35a4e90a, 0x0c3c8, 0x0db },  { 0x35a4e90c, 0x0c42c, 0x09f },
    { 0x35a4e90d, 0x0c42c, 0x0a0 },  { 0x35a4e909, 0x0c3c8, 0x0dc },
    { 0x127bc085, 0x0c3f3, 0x0f3 },  { 0x127bc086, 0x0c472, 0x0b9 },
    { 0x127bc087, 0x0c473, 0x0bc },  { 0x127bc088, 0x0c474, 0x0bf },
    { 0x127bc089, 0x0c454, 0x0cd },  { 0x127bc08a, 0x0c3f0, 0x0ed },
    { 0x11e39f35, 0x0c3e6, 0x0e7 },  { 0x35a4e91c, 0x18745, 0x000 },
    { 0x35a4e91d, 0x18746, 0x000 },  { 0x35a4e91e, 0x0c760, 0x000 },
    { 0x35a4e91f, 0x0c761, 0x000 },  { 0x35a4e920, 0x18749, 0x000 },
    { 0x35a4e921, 0x1874a, 0x000 },  { 0x35a4e922, 0x1874b, 0x000 },
    { 0x35a4e923, 0x0c756, 0x000 },  { 0x35a4e924, 0x1874c, 0x000 },
    { 0x35a4e925, 0x1874d, 0x000 },  { 0x35a4e926, 0x0c7b0, 0x000 },
    { 0x35a4e927, 0x0c7a6, 0x000 },  { 0x35a4e928, 0x18751, 0x000 },
    { 0x35a4e929, 0x18750, 0x000 },  { 0x35a4e92a, 0x1874f, 0x000 },
    { 0x35a4e92b, 0x18752, 0x000 },  { 0x35a4e92c, 0x18759, 0x000 },
    { 0x35a4e92d, 0x18753, 0x000 },  { 0x35a4e92e, 0x1874e, 0x000 },
    { 0x101a77f5, 0x0c404, 0x0fa },  { 0x10198d95, 0x0c3be, 0x0d5 },
    { 0x10198d97, 0x0c42d, 0x09d },  { 0x10198d9b, 0x0c423, 0x096 },
    { 0x10198d9c, 0x0c3c8, 0x000 },  { 0x101a29d5, 0x0c454, 0x000 },
    { 0x11e5c215, 0x0c441, 0x000 },  { 0x11e5c216, 0x0c3dc, 0x000 },
    { 0x11e61035, 0x0c4c2, 0x000 },  { 0x11e61036, 0x0c47c, 0x0c3 },
    { 0x15784f15, 0x0c404, 0x000 },  { 0x1577c276, 0x0c454, 0x000 },
    { 0x35a4e90e, 0x0c42c, 0x09b },  { 0x35a4e90f, 0x0c42c, 0x09c },
    { 0x35a4e910, 0x0c432, 0x0a4 },  { 0x35a4e911, 0x0c42c, 0x09d },
    { 0x35a4e912, 0x0c42c, 0x09a },  { 0x35a4e914, 0x0c422, 0x095 },
    { 0x35a4e915, 0x0c422, 0x094 },  { 0x35a4e916, 0x0c3be, 0x0d4 },
    { 0x35a4e917, 0x0c3be, 0x0d5 },  { 0x35a4e918, 0x0c3c8, 0x0d9 },
    { 0x35a4e919, 0x0c3c8, 0x0d7 },  { 0x35a4e91a, 0x0c3c8, 0x0da },
    { 0x35a4e913, 0x0c3c8, 0x0d8 },  { 0x35a4e91b, 0x0c42c, 0x0a1 },
    { 0x17dab8b5, 0x0c3e6, 0x000 },  { 0x35a4e906, 0x0c3f5, 0x000 },
    { 0x35a4e907, 0x0c4b8, 0x100 },
};
#define DRAMATIST_TABLE_COUNT (sizeof DRAMATIST_TABLE / sizeof DRAMATIST_TABLE[0])

const party_dramatist_row *party_dramatist_find(uint32_t handle)
{
    if (handle == 0) return NULL;        /* 0x41f200:54 guards on param_9 != 0 */
    for (size_t i = 0; i < DRAMATIST_TABLE_COUNT; i++)
        if (DRAMATIST_TABLE[i].handle == handle)
            return &DRAMATIST_TABLE[i];
    return NULL;
}

/*
 * The 0x41f200 per-archetype `if (sVar17 == 0)` default-bank arms, read off the
 * decompile (docs/decompiled/by-address/41f200.c).  Each archetype picks a sheet
 * by the facing selector param_11 (1/2/3 directional, else the base bank).  Only
 * the town-arrival archetypes + their immediate neighbours are modelled; the
 * 0x41f200 switch has hundreds of cases (PORT-DEBT dramatist-archetype-defaults).
 */
uint16_t party_archetype_default_bank(uint32_t code, int facing_sel)
{
    /* Each row: {code, base(else), f1, f2, f3}.  A 0 in an f-slot means the case
     * has no branch for that facing (it falls to the base, like the decompile's
     * 2-way `if/else` archetypes). */
    static const struct { uint32_t code; uint16_t base, f1, f2, f3; } DEF[] = {
        { 0xc3dc, 0xdd, 0xde, 0xdf, 0xe0 },  /* :1386 Father / man (3-dir)      */
        { 0xc3dd, 0xe1, 0xe2, 0,    0    },  /* :1402 (2-way: f1 else base)     */
        { 0xc3e6, 0xe5, 0xe6, 0xe7, 0    },  /* :1421 Guard                     */
        { 0xc3eb, 0xe8, 0xe9, 0xea, 0    },  /* :1434                           */
        { 0xc3f0, 0xeb, 0xec, 0xed, 0    },  /* :1456 Dr. Barnard               */
        { 0xc3f1, 0xee, 0xef, 0,    0    },  /* :1469                           */
        { 0xc3f2, 0xf0, 0xf1, 0,    0    },  /* :1479                           */
        { 0xc3f3, 0xf2, 0xf3, 0xf4, 0    },  /* :1497 Headmaster / Rowen        */
        { 0xc440, 0xa5, 0xa6, 0xa7, 0xa8 },  /* :1768 Woman (Mother archetype)  */
        { 0xc441, 0xa9, 0xaa, 0xab, 0xac },  /* :1801 Woman variant             */
    };
    for (size_t i = 0; i < sizeof DEF / sizeof DEF[0]; i++) {
        if (DEF[i].code != code) continue;
        uint16_t b;
        if      (facing_sel == 1) b = DEF[i].f1;
        else if (facing_sel == 2) b = DEF[i].f2;
        else if (facing_sel == 3) b = DEF[i].f3;
        else                      b = DEF[i].base;
        /* A missing directional branch (0) falls through to the base, exactly
         * as the decompile's narrower `if/else` cases do. */
        return (b != 0) ? b : DEF[i].base;
    }
    return 0;                         /* archetype not in the RE'd subset */
}

int party_resolve_spawn(uint32_t handle, uint32_t code_in, int facing_sel,
                        uint32_t *code_out, uint16_t *bank_out)
{
    uint32_t code = code_in;
    uint16_t bank = 0;                /* sVar17 starts 0 (0x41f200:42) */

    /* 0x41f200:54-69 — the dramatist lookup.  The spawn path (0x41f0e0) passes
     * the activator's param_4 = 3, so the row's code only overrides when the
     * caller spawned with code 0 (the `param_6 == 0` half of the :61 condition;
     * `param_4 == 1` is never true on this path). */
    const party_dramatist_row *row = party_dramatist_find(handle);
    if (row != NULL) {
        if (code_in == 0) code = row->code;
        bank = row->bank;             /* the OVERRIDE (sVar17 = row +0x30) */
    }

    /* Each archetype case: if no dramatist bank, take the per-facing default. */
    if (bank == 0)
        bank = party_archetype_default_bank(code, facing_sel);

    if (code_out) *code_out = code;
    if (bank_out) *bank_out = bank;
    return (bank != 0);
}

/* ══════════════════════════════════════════════════════════════════════════
 * Party band Phase 2 — the party-member stat accessors (see party.h).
 * Ported bit-for-bit from FUN_00494e60 (the reads) + FUN_00497b40/00497bb0 (the
 * displayed-number path).  NB retail's number helper uses the RAW 3-term sum for
 * the interpolation but max(1,sum) for the ratio comparison — both preserved.
 * ══════════════════════════════════════════════════════════════════════════ */

/* 494e60:109 — the displayed MAX HP = *(+0x9c)+*(+0x84)+*(+0x58) (raw sum, no
 * clamp: what "%s / %d" prints as the max). */
int party_stat_hp_max(const party_stats *s)
{
    return s->hp_base + s->hp_equip + s->hp_buff;
}

/* 494e60:116 — MAX MP = *(+0xa0)+*(+0x88)+*(+0x60). */
int party_stat_mp_max(const party_stats *s)
{
    return s->mp_base + s->mp_equip + s->mp_buff;
}

/* cur*1000/max(1,sum), clamped [0,1000] — the animator's (0x49af40) target ratio
 * (e.g. 49af40:42 `(*(+0x54)*1000)/max(1,sum)`). */
static int party_ratio(int cur, int sum)
{
    int denom = sum < 1 ? 1 : sum;
    int r = (cur * 1000) / denom;
    if (r < 0) r = 0;
    if (r > 1000) r = 1000;
    return r;
}

int party_stat_hp_ratio(const party_stats *s)
{
    return party_ratio(s->hp_cur, party_stat_hp_max(s));
}

int party_stat_mp_ratio(const party_stats *s)
{
    return party_ratio(s->mp_cur, party_stat_mp_max(s));
}

/* FUN_00497b40 — displayed CURRENT HP: exact cur when `ratio` matches the true
 * cur ratio, else the interpolated (raw_sum*ratio)/1000. */
int party_stat_hp_display(const party_stats *s, int ratio)
{
    int sum = party_stat_hp_max(s);          /* iVar1 (raw) */
    int denom = sum < 1 ? 1 : sum;           /* iVar2 */
    if (ratio == (s->hp_cur * 1000) / denom)
        return s->hp_cur;
    return (sum * ratio) / 1000;
}

/* FUN_00497bb0 — displayed CURRENT MP (the MP-field mirror of 497b40). */
int party_stat_mp_display(const party_stats *s, int ratio)
{
    int sum = party_stat_mp_max(s);
    int denom = sum < 1 ? 1 : sum;
    if (ratio == (s->mp_cur * 1000) / denom)
        return s->mp_cur;
    return (sum * ratio) / 1000;
}

/* 494e60:123 — the displayed char level = *(+0xe0) + *(+0xd8) = combat_level_max + level_bonus.
 * (+0xe0 alone is the MAX COMBAT LEVEL / star max — USER live SE — not the display level.) */
int party_stat_level(const party_stats *s)
{
    return s->combat_level_max + s->level_bonus;
}

/* The leader member (room+0x200c), or NULL when there is no active leader —
 * matching retail's slot gate (active==1 && handle != the empty sentinel). */
const party_member *party_leader(const party *p)
{
    if (p->leader < 0 || p->leader >= PARTY_SLOT_COUNT)
        return NULL;
    const party_member *m = &p->slots[p->leader];
    if (!m->active || m->handle == 0 || m->handle == PARTY_HANDLE_EMPTY)
        return NULL;
    return m;
}

/* FUN_00426fd0's (code,level) row select (426fd0:20-34): the first row whose
 * code matches and (level matches OR level==0), else the fallback row 0. */
const base_stat_row *base_stat_find(uint32_t code, int level)
{
    for (size_t i = 0; i < BASE_STAT_TABLE_COUNT; i++)
        if (BASE_STAT_TABLE[i].code == code &&
            (BASE_STAT_TABLE[i].level == level || level == 0))
            return &BASE_STAT_TABLE[i];
    return &BASE_STAT_TABLE[0];       /* retail: puVar8 = &DAT_0067ac58 (row 0) */
}

/* FUN_00426fd0 — the +0x750 field writes the HUD leader panel reads (the RPG
 * combat fields +0x64..+0x70 and the growth/RNG fields are not modelled here;
 * this is the HUD-read subset). */
void party_stats_init(party_stats *s, uint32_t code, int level)
{
    const base_stat_row *r = base_stat_find(code, level);
    /* 426fd0:167-172 — HP/MP base(+0x58/+0x60) = cur(+0x54/+0x5c) = the table max;
     * :119-166 clear the equip(+0x84/+0x88) and mod(+0x9c/+0xa0) terms. */
    s->hp_cur  = s->hp_base = r->hp;
    s->hp_equip = s->hp_buff = 0;
    s->mp_cur  = s->mp_base = r->mp;
    s->mp_equip = s->mp_buff = 0;
    /* 426fd0:109 combat_level_max(+0xe0) = row.level; :101-108 clear +0xd8/+0xdc
     * (level_bonus + element/star_count). */
    s->combat_level_max  = r->level;
    s->level_bonus = 0;
    s->star_count  = 0;
    /* 426fd0:96-100 EXP cur(+0xe8) = 0, max(+0xec) = row.exp_max. */
    s->exp_cur = 0;
    s->exp_max = r->exp_max;
}

void party_init_errands(party *p)
{
    for (int i = 0; i < PARTY_SLOT_COUNT; i++)
        p->slots[i] = (party_member){0};
    p->leader = -1;

    /* slot 0 = Arche, the lone errands party member + leader.  Retail
     * FUN_004cc820(slot 0, code 0, level 1, handle 0x5f5e165, element 2, active 1)
     * resolves code 0 from the handle (0x5f5e165 -> dramatist code 0xc35a). */
    const party_dramatist_row *arche = party_dramatist_find(0x5f5e165u);
    uint32_t code = (arche != NULL) ? arche->code : 0xc35au;
    p->slots[0].handle = 0x5f5e165u;
    p->slots[0].active = 1;
    party_stats_init(&p->slots[0].stats, code, 1);
    /* PORT-DEBT(hud-party-context): the element-star COUNT (+0xdc) is set by the
     * UNPORTED equip/element-affinity recompute — NOT the base table, and NOT any
     * scene dispatcher.  BOTH char-init paths CLEAR it (426fd0:105 + 4c5e00:85),
     * and every non-zero +0xdc write in the corpus is a scene-beat index on the
     * scene object (*in_ECX), not the stats block.  The setter VA is unidentified
     * (the plan's "FUN_004f19e0" was WRONG — 4f19e0 is the Weathervane Tower story
     * script); find it via a live mem_watch on the leader stats+0xdc.  Arche's 2
     * errands stars stay a stand-in until that lands.  HP/MP/level/EXP are real. */
    p->slots[0].stats.star_count = 2;
    p->leader = 0;
}
