/*
 * party.c — see party.h.  The dramatist table DAT_006b6ea8 + the 0x41f200
 * spawn-time handle->code/bank resolution (the chip that makes a NAMED character
 * render its own sheet instead of the archetype's generic townsperson default).
 */
#include "party.h"

#include <stddef.h>

/*
 * The retail "Get Dramatist Info" table DAT_006b6ea8 (image base 0x400000,
 * file off 0x2b6ea8), generated by tools/dump_dramatist_table.py from the
 * user's own vendor/unpacked/sotes.unpacked.exe.  79 rows, handle==0 terminated
 * in retail (the count is fixed here).
 *
 * NUMERIC RE facts only (handle / code / bank — like every other resolved table
 * in the port, e.g. asset_register.c's resource-id maps).  The character NAMES
 * are story content: they are NOT embedded here — they live in the documentation
 * (docs/proofs/dramatist-table.md) and regenerate from the user's own binary via
 * the dump tool.  The arrival cast this module renders, by handle:
 *   0x05f5e165 Arche (leader, party-loaded)   0x05f5e1d3 Arche's Father (-> 0xe3)
 *   0x05f5e1d4 Arche's Mother (-> 0xb5)        0x35a4e901 Dr. Barnard
 *   0x0c878d35 the Guard
 * Regenerate the rows: tools/dump_dramatist_table.py (then strip the name column).
 */
static const party_dramatist_row DRAMATIST_TABLE[] = {
    { 0x05f5e165, 0x0c35a, 0x000 },  { 0x05f5e166, 0x0c35b, 0x000 },
    { 0x05f5e167, 0x0c35c, 0x000 },  { 0x05f5e168, 0x0c35d, 0x000 },
    { 0x05f5e1d3, 0x0c3dc, 0x0e3 },  { 0x05f5e1d4, 0x0c440, 0x0b5 },
    { 0x35a4e902, 0x0c440, 0x0b4 },  { 0x35a4e903, 0x0c440, 0x0b3 },
    { 0x35a4e904, 0x0c3dc, 0x0e4 },  { 0x35a4e905, 0x0c3f3, 0x0f4 },
    { 0x0c86c9e5, 0x0c3f1, 0x000 },  { 0x0c873f15, 0x0c440, 0x0ab },
    { 0x0c86f0f5, 0x0c440, 0x0a7 },  { 0x0c86a2d5, 0x0c454, 0x0ce },
    { 0x0c878d35, 0x0c3e6, 0x0e6 },  { 0x35a4e901, 0x0c3f0, 0x0ec },
    { 0x0c86c9e6, 0x0c443, 0x000 },  { 0x0db75aa5, 0x0e2a8, 0x000 },
    { 0x35a4e908, 0x0c3be, 0x0d6 },  { 0x35a4e90b, 0x0c42c, 0x09e },
    { 0x35a4e90a, 0x0c3c8, 0x0db },  { 0x35a4e90c, 0x0c42c, 0x09f },
    { 0x35a4e90d, 0x0c42c, 0x0a0 },  { 0x35a4e909, 0x0c3c8, 0x0dc },
    { 0x127bc085, 0x0c3f3, 0x0f3 },  { 0x127bc086, 0x0c472, 0x0b9 },
    { 0x127bc087, 0x0c473, 0x0bc },  { 0x127bc088, 0x0c474, 0x0bf },
    { 0x127bc089, 0x0c454, 0x0cd },  { 0x127bc08a, 0x0c3f0, 0x0ed },
    { 0x11e39f35, 0x0c3e6, 0x0e7 },  { 0x35a4e91c, 0x18745, 0x000 },
    { 0x35a4e91d, 0x18746, 0x000 },  { 0x35a4e91e, 0x0c760, 0x000 },
    { 0x35a4e91f, 0x0c761, 0x000 },  { 0x35a4e920, 0x18749, 0x000 },
    { 0x35a4e921, 0x1874a, 0x000 },  { 0x35a4e922, 0x1874b, 0x000 },
    { 0x35a4e923, 0x0c756, 0x000 },  { 0x35a4e924, 0x1874c, 0x000 },
    { 0x35a4e925, 0x1874d, 0x000 },  { 0x35a4e926, 0x0c7b0, 0x000 },
    { 0x35a4e927, 0x0c7a6, 0x000 },  { 0x35a4e928, 0x18751, 0x000 },
    { 0x35a4e929, 0x18750, 0x000 },  { 0x35a4e92a, 0x1874f, 0x000 },
    { 0x35a4e92b, 0x18752, 0x000 },  { 0x35a4e92c, 0x18759, 0x000 },
    { 0x35a4e92d, 0x18753, 0x000 },  { 0x35a4e92e, 0x1874e, 0x000 },
    { 0x101a77f5, 0x0c404, 0x0fa },  { 0x10198d95, 0x0c3be, 0x0d5 },
    { 0x10198d97, 0x0c42d, 0x09d },  { 0x10198d9b, 0x0c423, 0x096 },
    { 0x10198d9c, 0x0c3c8, 0x000 },  { 0x101a29d5, 0x0c454, 0x000 },
    { 0x11e5c215, 0x0c441, 0x000 },  { 0x11e5c216, 0x0c3dc, 0x000 },
    { 0x11e61035, 0x0c4c2, 0x000 },  { 0x11e61036, 0x0c47c, 0x0c3 },
    { 0x15784f15, 0x0c404, 0x000 },  { 0x1577c276, 0x0c454, 0x000 },
    { 0x35a4e90e, 0x0c42c, 0x09b },  { 0x35a4e90f, 0x0c42c, 0x09c },
    { 0x35a4e910, 0x0c432, 0x0a4 },  { 0x35a4e911, 0x0c42c, 0x09d },
    { 0x35a4e912, 0x0c42c, 0x09a },  { 0x35a4e914, 0x0c422, 0x095 },
    { 0x35a4e915, 0x0c422, 0x094 },  { 0x35a4e916, 0x0c3be, 0x0d4 },
    { 0x35a4e917, 0x0c3be, 0x0d5 },  { 0x35a4e918, 0x0c3c8, 0x0d9 },
    { 0x35a4e919, 0x0c3c8, 0x0d7 },  { 0x35a4e91a, 0x0c3c8, 0x0da },
    { 0x35a4e913, 0x0c3c8, 0x0d8 },  { 0x35a4e91b, 0x0c42c, 0x0a1 },
    { 0x17dab8b5, 0x0c3e6, 0x000 },  { 0x35a4e906, 0x0c3f5, 0x000 },
    { 0x35a4e907, 0x0c4b8, 0x100 },
};
#define DRAMATIST_TABLE_COUNT (sizeof DRAMATIST_TABLE / sizeof DRAMATIST_TABLE[0])

const party_dramatist_row *party_dramatist_find(uint32_t handle)
{
    if (handle == 0) return NULL;        /* 0x41f200:54 guards on param_9 != 0 */
    for (size_t i = 0; i < DRAMATIST_TABLE_COUNT; i++)
        if (DRAMATIST_TABLE[i].handle == handle)
            return &DRAMATIST_TABLE[i];
    return NULL;
}

/*
 * The 0x41f200 per-archetype `if (sVar17 == 0)` default-bank arms, read off the
 * decompile (docs/decompiled/by-address/41f200.c).  Each archetype picks a sheet
 * by the facing selector param_11 (1/2/3 directional, else the base bank).  Only
 * the town-arrival archetypes + their immediate neighbours are modelled; the
 * 0x41f200 switch has hundreds of cases (PORT-DEBT dramatist-archetype-defaults).
 */
uint16_t party_archetype_default_bank(uint32_t code, int facing_sel)
{
    /* Each row: {code, base(else), f1, f2, f3}.  A 0 in an f-slot means the case
     * has no branch for that facing (it falls to the base, like the decompile's
     * 2-way `if/else` archetypes). */
    static const struct { uint32_t code; uint16_t base, f1, f2, f3; } DEF[] = {
        { 0xc3dc, 0xdd, 0xde, 0xdf, 0xe0 },  /* :1386 Father / man (3-dir)      */
        { 0xc3dd, 0xe1, 0xe2, 0,    0    },  /* :1402 (2-way: f1 else base)     */
        { 0xc3e6, 0xe5, 0xe6, 0xe7, 0    },  /* :1421 Guard                     */
        { 0xc3eb, 0xe8, 0xe9, 0xea, 0    },  /* :1434                           */
        { 0xc3f0, 0xeb, 0xec, 0xed, 0    },  /* :1456 Dr. Barnard               */
        { 0xc3f1, 0xee, 0xef, 0,    0    },  /* :1469                           */
        { 0xc3f2, 0xf0, 0xf1, 0,    0    },  /* :1479                           */
        { 0xc3f3, 0xf2, 0xf3, 0xf4, 0    },  /* :1497 Headmaster / Rowen        */
        { 0xc440, 0xa5, 0xa6, 0xa7, 0xa8 },  /* :1768 Woman (Mother archetype)  */
        { 0xc441, 0xa9, 0xaa, 0xab, 0xac },  /* :1801 Woman variant             */
    };
    for (size_t i = 0; i < sizeof DEF / sizeof DEF[0]; i++) {
        if (DEF[i].code != code) continue;
        uint16_t b;
        if      (facing_sel == 1) b = DEF[i].f1;
        else if (facing_sel == 2) b = DEF[i].f2;
        else if (facing_sel == 3) b = DEF[i].f3;
        else                      b = DEF[i].base;
        /* A missing directional branch (0) falls through to the base, exactly
         * as the decompile's narrower `if/else` cases do. */
        return (b != 0) ? b : DEF[i].base;
    }
    return 0;                         /* archetype not in the RE'd subset */
}

int party_resolve_spawn(uint32_t handle, uint32_t code_in, int facing_sel,
                        uint32_t *code_out, uint16_t *bank_out)
{
    uint32_t code = code_in;
    uint16_t bank = 0;                /* sVar17 starts 0 (0x41f200:42) */

    /* 0x41f200:54-69 — the dramatist lookup.  The spawn path (0x41f0e0) passes
     * the activator's param_4 = 3, so the row's code only overrides when the
     * caller spawned with code 0 (the `param_6 == 0` half of the :61 condition;
     * `param_4 == 1` is never true on this path). */
    const party_dramatist_row *row = party_dramatist_find(handle);
    if (row != NULL) {
        if (code_in == 0) code = row->code;
        bank = row->bank;             /* the OVERRIDE (sVar17 = row +0x30) */
    }

    /* Each archetype case: if no dramatist bank, take the per-facing default. */
    if (bank == 0)
        bank = party_archetype_default_bank(code, facing_sel);

    if (code_out) *code_out = code;
    if (bank_out) *bank_out = bank;
    return (bank != 0);
}
